/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface_ManageAirline;

import Business.Airline;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author ragha
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirlinerJPanel
     */
    private JPanel userContainer;
            private Airline airline;
               

    
    public ViewAirlinerJPanel(JPanel userContainer, Airline airline) {
        initComponents();
        this.userContainer  = userContainer;
        this.airline = airline;
       saveButton.setEnabled(false);
        updateButton.setEnabled(true);
                populateAirlineDetails();

    }

   private void populateAirlineDetails()
   {
       airlineName.setText(airline.getName());
       airlineAddressText.setText(airline.getAddress());
       airlinenumFlightsText.setText(String.valueOf(airline.getNoOfFlights()));
       airlineSerialText.setText(airline.getSerialNum());
   }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        airlineName = new javax.swing.JLabel();
        numFlightsLabel = new javax.swing.JLabel();
        serialLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        airlineAddressText = new javax.swing.JTextField();
        airlinenumFlightsText = new javax.swing.JTextField();
        airlineSerialText = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("View Airliner");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, -1, -1));
        add(airlineName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 210, 30));

        numFlightsLabel.setText("Number Of Flights");
        add(numFlightsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 280, 130, -1));

        serialLabel.setText("Serial Number");
        add(serialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 130, -1));

        addressLabel.setText("Address");
        add(addressLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, -1));

        airlineAddressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                airlineAddressTextActionPerformed(evt);
            }
        });
        add(airlineAddressText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 330, 180, -1));
        add(airlinenumFlightsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 180, -1));
        add(airlineSerialText, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 180, -1));

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        add(saveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 434, -1, -1));

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 434, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void airlineAddressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_airlineAddressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_airlineAddressTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Go to the previous page
        userContainer.remove(this);
        Component[] componentArray = userContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageAirlineJPanel manageAccountJPanel = (ManageAirlineJPanel) component;
        manageAccountJPanel.populateTable();
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Save

        if(airlineSerialText.getText()==null  || airlinenumFlightsText.getText() == null
            || airlineAddressText.getText() ==null  )
        {
            JOptionPane.showMessageDialog(null, "Enter all the details" , "Warning", JOptionPane.WARNING_MESSAGE);

        }
        else {
            airline.setAddress(airlineAddressText.getText());
            airline.setNoOfFlights(Integer.parseInt(airlinenumFlightsText.getText()));
            airline.setSerialNum(airlineSerialText.getText());
            saveButton.setEnabled(false);
            updateButton.setEnabled(true);
            airlineAddressText.setEnabled(false);
            airlinenumFlightsText.setEnabled(false);
            airlineSerialText.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Airline details updated successfully ! " , "Airline Updation", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        airlineAddressText.setEnabled(true);
        airlineSerialText.setEnabled(true);
        airlinenumFlightsText.setEnabled(true);
        saveButton.setEnabled(true);
        updateButton.setEnabled(false);
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField airlineAddressText;
    private javax.swing.JLabel airlineName;
    private javax.swing.JTextField airlineSerialText;
    private javax.swing.JTextField airlinenumFlightsText;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel numFlightsLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel serialLabel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
