/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacePackage;

import BusinessPackage.Airplane;
import BusinessPackage.Fleet;
import java.sql.Date;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ragha
 */
public class CreateAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateAirplaneJPanel
     */
    private Fleet fleet;
    public CreateAirplaneJPanel(Fleet fleet) {
        initComponents();
        //Button Group for Availability Status
        buttonGroupForAvailability.add(availableRadioButton);
        buttonGroupForAvailability.add(notAvailableRadioButton);
        //Button Group for Maintanance Certficate Expiry Status
        buttonGroupForCertificate.add(expiredRadioButton);
        buttonGroupForCertificate.add(validRadioButton);
        this.fleet=fleet;
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupForAvailability = new javax.swing.ButtonGroup();
        buttonGroupForCertificate = new javax.swing.ButtonGroup();
        createLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        manufacturerTextField = new javax.swing.JTextField();
        seatsTextField = new javax.swing.JTextField();
        serialNumTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        manufactureDateTxt = new javax.swing.JTextField();
        submitButton = new javax.swing.JButton();
        availableRadioButton = new javax.swing.JRadioButton();
        notAvailableRadioButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        expiredRadioButton = new javax.swing.JRadioButton();
        validRadioButton = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createLabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        createLabel.setText("Create Airplane Entry");
        createLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(createLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, 400, -1));

        jLabel1.setText("Manufacturer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jLabel2.setText("No of seats");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));

        jLabel3.setText("Serial Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        jLabel4.setText("Model Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabel5.setText("Manufacture Date");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, -1));
        add(manufacturerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 280, -1));
        add(seatsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 280, -1));
        add(serialNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 280, -1));
        add(modelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 290, 280, -1));
        add(manufactureDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 280, -1));

        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 630, -1, -1));

        availableRadioButton.setText("Yes");
        add(availableRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, -1, -1));

        notAvailableRadioButton.setText("No");
        add(notAvailableRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, -1, -1));

        jLabel6.setText("Availability");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        jLabel7.setText("Maintanence Certificate");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        expiredRadioButton.setText("Expired");
        add(expiredRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, -1, -1));

        validRadioButton.setText("Valid");
        add(validRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 440, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        // Save it in the ArrayList of type Airplane
         DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        Airplane airplane = fleet.addAirplane();
        try {
            airplane.setAirplaneManufactureDate(df.parse(manufactureDateTxt.getText()));
        } catch (ParseException ex) {
            Logger.getLogger(CreateAirplaneJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        airplane.setAirplaneManufacturer(manufacturerTextField.getText());
        airplane.setAirplaneModelNum(modelTextField.getText());
        airplane.setAirplaneSeats(Integer.parseInt(seatsTextField.getText()));
        airplane.setAirplaneSerialNum(serialNumTextField.getText());
        if(availableRadioButton.isEnabled())
        {
                    airplane.setIsAvailable(Boolean.TRUE);

        }
        else
        {
            airplane.setIsAvailable(Boolean.FALSE);
        }
        if(expiredRadioButton.isEnabled())
        {
        airplane.setIsExpired(Boolean.TRUE);
        }
        else{
                    airplane.setIsExpired(Boolean.FALSE);

        }
        JOptionPane.showMessageDialog(null, "Airplane Entry Added");
         
        manufacturerTextField.setText("");
        modelTextField.setText("");
        seatsTextField.setText("");
        serialNumTextField.setText("");
        manufactureDateTxt.setText("");
        buttonGroupForAvailability.clearSelection();
        buttonGroupForCertificate.clearSelection();
        
    }//GEN-LAST:event_submitButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton availableRadioButton;
    private javax.swing.ButtonGroup buttonGroupForAvailability;
    private javax.swing.ButtonGroup buttonGroupForCertificate;
    private javax.swing.JLabel createLabel;
    private javax.swing.JRadioButton expiredRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField manufactureDateTxt;
    private javax.swing.JTextField manufacturerTextField;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JRadioButton notAvailableRadioButton;
    private javax.swing.JTextField seatsTextField;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JButton submitButton;
    private javax.swing.JRadioButton validRadioButton;
    // End of variables declaration//GEN-END:variables
}
