/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacePackage;

import BusinessPackage.Airplane;
import BusinessPackage.Fleet;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.net.URL;
import java.util.Date;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;

/**
 *
 * @author ragha
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    private Fleet fleet;

    public MainJFrame() {
        initComponents();
        fleet = new Fleet();
        populateFleetCatalogFromCSV();
    }

    public void populateFleetCatalogFromCSV() {
        //Load the CSV 
        URL url = getClass().getResource("Book1.csv");
        File file = new File(url.getPath());
        BufferedReader fileReader = null;
        final String DELIMITER = ",";
        try {
            String line = "";
            //Create the file reader
            fileReader = new BufferedReader(new FileReader(file));

            //Read the file line by line
            while ((line = fileReader.readLine()) != null) {
                //Get all tokens available in line

                String[] tokens = line.split(DELIMITER);
                // for (String token : tokens) {
                //  String a= tokens[0];
                //Print all tokens
                //   System.out.println(token);
                Airplane airplane = fleet.addAirplane();

                airplane.setAirplaneName(tokens[0]);
                airplane.setAirplaneManufacturer(tokens[1]);
                airplane.setAirplaneSeats(Integer.parseInt(tokens[2]));
                airplane.setAirplaneSerialNum(tokens[3]);

                airplane.setAirplaneModelNum(tokens[4]);
                String date = tokens[5];
                Date date1 = (Date) new SimpleDateFormat("dd/MM/yyyy").parse(date);
                airplane.setAirplaneManufactureDate(date1);
                //  System.out.println(tokens[7]);
                if (tokens[6].equalsIgnoreCase("true")) {
                    airplane.setIsAvailable(Boolean.TRUE);
                } else {
                    airplane.setIsAvailable(Boolean.FALSE);

                }
                if (tokens[7].equalsIgnoreCase("Valid")) {
                    airplane.setIsExpired(Boolean.FALSE);
                } else {
                    airplane.setIsExpired(Boolean.TRUE);

                }
                airplane.setAirportName(tokens[8]);
                String date2 = tokens[9];
                Date date_2 = (Date) new SimpleDateFormat("MM/dd/yyyy").parse(date2);

                airplane.setAvailabityDate(date_2);

            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        createAirplaneButton = new javax.swing.JButton();
        viewAirplaneButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createAirplaneButton.setText("Create");
        createAirplaneButton.setToolTipText("Add Airplane Entry");
        createAirplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAirplaneButtonActionPerformed(evt);
            }
        });

        viewAirplaneButton.setText("View/Update");
        viewAirplaneButton.setToolTipText("Update and View Fleet Catalog");
        viewAirplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirplaneButtonActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.setToolTipText("Search Operation on Fleet Catalog");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createAirplaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewAirplaneButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(createAirplaneButton)
                .addGap(42, 42, 42)
                .addComponent(viewAirplaneButton)
                .addGap(40, 40, 40)
                .addComponent(searchButton)
                .addContainerGap(225, Short.MAX_VALUE))
        );

        splitPane.setLeftComponent(leftPanel);

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(rightPanel);

        getContentPane().add(splitPane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAirplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAirplaneButtonActionPerformed
        // CreateAirplane JForm should appear at the right component
        CreateAirplaneJPanel createAirplaneJPanel = new CreateAirplaneJPanel(fleet);
        splitPane.setRightComponent(createAirplaneJPanel);

    }//GEN-LAST:event_createAirplaneButtonActionPerformed

    private void viewAirplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirplaneButtonActionPerformed
        // ViewAirplane JForm should appear at the right component
        ViewAirplaneJPanel viewAirplaneJPanel = new ViewAirplaneJPanel(fleet);
        splitPane.setRightComponent(viewAirplaneJPanel);
    }//GEN-LAST:event_viewAirplaneButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        Search searchJPanel = new Search(fleet);
        splitPane.setRightComponent(searchJPanel);
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAirplaneButton;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JButton viewAirplaneButton;
    // End of variables declaration//GEN-END:variables
}
