/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacePackage;

import BusinessPackage.Airplane;
import BusinessPackage.Fleet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ragha
 */
public class Search extends javax.swing.JPanel {

    /**
     * Creates new form Search
     */
    private Fleet fleet;

    public Search(Fleet fleet) {
        initComponents();
        setVisibleFalse();
        this.fleet = fleet;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplaneTableForSearch = new javax.swing.JTable();
        labelForManufacturer = new javax.swing.JLabel();
        seatsLabel = new javax.swing.JLabel();
        serialNumLabel = new javax.swing.JLabel();
        modelNumLabel = new javax.swing.JLabel();
        manuDateLabel = new javax.swing.JLabel();
        manufacturerTextField = new javax.swing.JTextField();
        seatsTextField = new javax.swing.JTextField();
        serialNumTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        manufactureDateTxt = new javax.swing.JTextField();
        avaiStatusLabel = new javax.swing.JLabel();
        isAvailableTextField = new javax.swing.JTextField();
        certiLabel = new javax.swing.JLabel();
        certificateStatusText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        countLabel = new javax.swing.JLabel();
        timeStampButton = new javax.swing.JButton();
        labelForTimeStamp = new javax.swing.JLabel();
        seatsearchLabel = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        minSeatTextBox = new javax.swing.JTextField();
        maxSeatTextField = new javax.swing.JTextField();
        seatSearch = new javax.swing.JButton();
        airportLabel = new javax.swing.JLabel();
        airportTextField = new javax.swing.JTextField();
        avaiStatusButton1 = new javax.swing.JButton();
        airportComboBox = new javax.swing.JComboBox<>();
        avaiLabel = new javax.swing.JLabel();
        avaiDateTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listForOneColumn = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        searchComboBox = new javax.swing.JComboBox<>();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Search ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 180, -1));

        searchText.setToolTipText("Give the serial number of the airplane");
        add(searchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 180, -1));

        airplaneTableForSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Name", "Model Number", "Serial Number", "Manufacturer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        airplaneTableForSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                airplaneTableForSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(airplaneTableForSearch);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 630, 330));

        labelForManufacturer.setText("Manufacturer");
        add(labelForManufacturer, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 680, -1, -1));

        seatsLabel.setText("No of seats");
        add(seatsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 740, -1, -1));

        serialNumLabel.setText("Serial Number");
        add(serialNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 790, -1, -1));

        modelNumLabel.setText("Model Number");
        add(modelNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 840, -1, -1));

        manuDateLabel.setText("Manufacture Date");
        add(manuDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 690, -1, -1));

        manufacturerTextField.setEditable(false);
        manufacturerTextField.setEnabled(false);
        add(manufacturerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 680, 280, -1));

        seatsTextField.setEnabled(false);
        add(seatsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 730, 280, -1));

        serialNumTextField.setEnabled(false);
        add(serialNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 780, 280, -1));

        modelTextField.setEnabled(false);
        add(modelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 840, 280, -1));

        manufactureDateTxt.setEnabled(false);
        add(manufactureDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 680, 280, -1));

        avaiStatusLabel.setText("Availability Status");
        add(avaiStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 740, -1, -1));

        isAvailableTextField.setEnabled(false);
        add(isAvailableTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 730, 280, -1));

        certiLabel.setText("Maintenance Certificate");
        add(certiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 790, -1, -1));

        certificateStatusText.setEnabled(false);
        add(certificateStatusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 780, 280, -1));

        nameLabel.setText("Name");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 630, -1, -1));

        nameTextField.setEditable(false);
        nameTextField.setEnabled(false);
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 630, 280, -1));
        add(countLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 480, 290, -1));

        timeStampButton.setText("Time Stamp for last updation of Fleet Catalog");
        timeStampButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeStampButtonActionPerformed(evt);
            }
        });
        add(timeStampButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 430, -1));
        add(labelForTimeStamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 550, 490, 30));

        seatsearchLabel.setText("Search via Seat Number ");
        add(seatsearchLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        statusLabel.setText(" ");
        add(statusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 540, 180, -1));

        minSeatTextBox.setToolTipText("Give the serial number of the airplane");
        add(minSeatTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 50, -1));

        maxSeatTextField.setToolTipText("Give the serial number of the airplane");
        add(maxSeatTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 50, -1));

        seatSearch.setText("Search");
        seatSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatSearchActionPerformed(evt);
            }
        });
        add(seatSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        airportLabel.setText("Airport");
        add(airportLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 840, -1, -1));

        airportTextField.setToolTipText("Give the value as either \"Expired\" or \"Valid\"");
        airportTextField.setEnabled(false);
        add(airportTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 830, 280, -1));

        avaiStatusButton1.setText("Airport Name");
        avaiStatusButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                avaiStatusButton1ActionPerformed(evt);
            }
        });
        add(avaiStatusButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 180, -1));

        airportComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dallas/Fort Worth International Airport", "Logan International Airport", "LaGuardia Airport", "Washington Dulles International Airport", "San Francisco International Airport", "John F. Kennedy International Airport", "Los Angeles International Airport", " " }));
        add(airportComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 250, -1));

        avaiLabel.setText("Availablity Date");
        add(avaiLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, -1, -1));

        avaiDateTextField.setToolTipText("Give the value as either \"Expired\" or \"Valid\"");
        avaiDateTextField.setEnabled(false);
        add(avaiDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, 280, -1));

        listForOneColumn.setEnabled(false);
        listForOneColumn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listForOneColumnMouseClicked(evt);
            }
        });
        listForOneColumn.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listForOneColumnValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listForOneColumn);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 630, 230, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 130, 150, -1));

        searchComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Serial Number", "Manufacture Year", "Model Number", "Expired Maintenance Certificate", "Boeing Manufacturer", "Airplane Availability", "First Available Airplane", "Manufacturers of the Airline" }));
        searchComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchComboBoxActionPerformed(evt);
            }
        });
        add(searchComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 150, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void airplaneTableForSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_airplaneTableForSearchMouseClicked
        countLabel.setVisible(false);
        labelForTimeStamp.setVisible(false);
        listForOneColumn.setVisible(Boolean.FALSE);
        listForOneColumn.setEnabled(false);
        listForOneColumn.clearSelection();
        int selectedRow = airplaneTableForSearch.getSelectedRow();
        if (selectedRow >= 0) {
            setVisibleTrue();
            Airplane airplane = (Airplane) airplaneTableForSearch.getValueAt((Integer) selectedRow, 0);
            nameTextField.setText(airplane.getAirplaneName());
            manufactureDateTxt.setText(String.valueOf(airplane.getAirplaneManufactureDate()));
            manufacturerTextField.setText(airplane.getAirplaneManufacturer());
            seatsTextField.setText(Integer.toString(airplane.getAirplaneSeats()));
            serialNumTextField.setText(airplane.getAirplaneSerialNum());
            modelTextField.setText(airplane.getAirplaneModelNum());
            isAvailableTextField.setText(airplane.getIsAvailable().toString());
            airportTextField.setText(airplane.getAirportName());
            if ((airplane.getIsExpired().toString()).equalsIgnoreCase("true")) {
                certificateStatusText.setText("Expired");
            } else {
                certificateStatusText.setText("Valid");
            }
            avaiDateTextField.setText(String.valueOf(airplane.getAvailabityDate()));
        }
    }//GEN-LAST:event_airplaneTableForSearchMouseClicked

    private void timeStampButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeStampButtonActionPerformed
        setVisibleFalse();
        listForOneColumn.setVisible(false);
        countLabel.setVisible(false);
        for (Airplane airplane : fleet.getFleet()) {
            labelForTimeStamp.setText("Catalog Last updated on : " + fleet.getTimeStamp());
            break;
        }

    }//GEN-LAST:event_timeStampButtonActionPerformed

    private void seatSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatSearchActionPerformed
        countLabel.setVisible(false);
        labelForTimeStamp.setVisible(false);
        listForOneColumn.setVisible(false);

        DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();
        defaultModel.setRowCount(0);
        int minSeats = Integer.parseInt(minSeatTextBox.getText());
        int maxSeats = Integer.parseInt(maxSeatTextField.getText());
        for (Airplane airplane : fleet.getFleet()) {
            if ((airplane.getAirplaneSeats() > minSeats) && (airplane.getAirplaneSeats() < maxSeats)) {
                Object row[] = new Object[4];
                row[0] = airplane;
                row[1] = airplane.getAirplaneModelNum();
                row[2] = airplane.getAirplaneSerialNum();
                row[3] = airplane.getAirplaneManufacturer();

                defaultModel.addRow(row);
            }
        }
    }//GEN-LAST:event_seatSearchActionPerformed

    private void avaiStatusButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_avaiStatusButton1ActionPerformed
        countLabel.setVisible(false);
        labelForTimeStamp.setVisible(false);
        listForOneColumn.setVisible(false);

        DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();
        defaultModel.setRowCount(0);
        String tobeSearched = airportComboBox.getSelectedItem().toString();
        for (Airplane airplane : fleet.getFleet()) {
            if (airplane.getAirportName().equalsIgnoreCase(tobeSearched)) {
                Object row[] = new Object[4];
                row[0] = airplane;
                row[1] = airplane.getAirplaneModelNum();
                row[2] = airplane.getAirplaneSerialNum();
                row[3] = airplane.getAirplaneManufacturer();

                defaultModel.addRow(row);
            }
        }
    }//GEN-LAST:event_avaiStatusButton1ActionPerformed

    private void listForOneColumnValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listForOneColumnValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_listForOneColumnValueChanged

    private void listForOneColumnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listForOneColumnMouseClicked
        countLabel.setVisible(false);
        labelForTimeStamp.setVisible(false);
        String airplaneName = listForOneColumn.getSelectedValue();
        for (Airplane airplane : fleet.getFleet()) {
            if (airplane.getAirplaneName().equals(airplaneName)) {
                setVisibleTrue();
                nameTextField.setText(airplane.getAirplaneName());
                manufactureDateTxt.setText(String.valueOf(airplane.getAirplaneManufactureDate()));
                manufacturerTextField.setText(airplane.getAirplaneManufacturer());
                seatsTextField.setText(Integer.toString(airplane.getAirplaneSeats()));
                serialNumTextField.setText(airplane.getAirplaneSerialNum());
                modelTextField.setText(airplane.getAirplaneModelNum());
                isAvailableTextField.setText(airplane.getIsAvailable().toString());
                airportTextField.setText(airplane.getAirportName());
                if ((airplane.getIsExpired().toString()).equalsIgnoreCase("true")) {
                    certificateStatusText.setText("Expired");
                } else {
                    certificateStatusText.setText("Valid");
                }
                avaiDateTextField.setText(String.valueOf(airplane.getAvailabityDate()));

            }
        }

    }//GEN-LAST:event_listForOneColumnMouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(((DefaultTableModel) airplaneTableForSearch.getModel()));
        sorter.setRowFilter(RowFilter.regexFilter(jTextField1.getText()));

        airplaneTableForSearch.setRowSorter(sorter);
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void searchComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchComboBoxActionPerformed
        if (searchComboBox.getSelectedItem().toString().equals("Serial Number")) {
            countLabel.setVisible(false);
            labelForTimeStamp.setVisible(false);
            listForOneColumn.setVisible(false);
                        searchText.setEditable(true);


            DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();
            defaultModel.setRowCount(0);
            String toBeSearched = searchText.getText();
            for (Airplane airplane : fleet.getFleet()) {
                if (airplane.getAirplaneSerialNum().equalsIgnoreCase(toBeSearched)) {
                    Object row[] = new Object[4];
                    row[0] = airplane;
                    row[1] = airplane.getAirplaneModelNum();
                    row[2] = airplane.getAirplaneSerialNum();
                    row[3] = airplane.getAirplaneManufacturer();

                    defaultModel.addRow(row);
                }
            }
        }
        if (searchComboBox.getSelectedItem().toString().equals("Manufacture Year")) {
            countLabel.setVisible(false);
            labelForTimeStamp.setVisible(false);
            listForOneColumn.setVisible(false);
                        searchText.setEditable(true);


            DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();
            defaultModel.setRowCount(0);
            String toBeSearched = searchText.getText();
            for (Airplane airplane : fleet.getFleet()) {
                // System.out.println(airplane.getAirplaneManufactureDate());  
                if ((airplane.getAirplaneManufactureDate().toString()).contains(toBeSearched)) {
                    Object row[] = new Object[4];
                    row[0] = airplane;
                    row[1] = airplane.getAirplaneModelNum();
                    row[2] = airplane.getAirplaneSerialNum();
                    row[3] = airplane.getAirplaneManufacturer();

                    defaultModel.addRow(row);
                }
            }
        }
        if (searchComboBox.getSelectedItem().toString().equals("Model Number")) {
            countLabel.setVisible(false);
            labelForTimeStamp.setVisible(false);
            listForOneColumn.setVisible(false);
                        searchText.setEditable(true);


            DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();
            defaultModel.setRowCount(0);
            String toBeSearched = searchText.getText();
            for (Airplane airplane : fleet.getFleet()) {
                if (airplane.getAirplaneModelNum().equalsIgnoreCase(toBeSearched)) {
                    Object row[] = new Object[4];
                    row[0] = airplane;
                    row[1] = airplane.getAirplaneModelNum();
                    row[2] = airplane.getAirplaneSerialNum();
                    row[3] = airplane.getAirplaneManufacturer();

                    defaultModel.addRow(row);
                }
            }

    }//GEN-LAST:event_searchComboBoxActionPerformed
        if (searchComboBox.getSelectedItem().toString().equals("Expired Maintenance Certificate")) {
            countLabel.setVisible(false);
            labelForTimeStamp.setVisible(false);
            listForOneColumn.setVisible(false);
            searchText.setEditable(false);

            DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();
            defaultModel.setRowCount(0);
            for (Airplane airplane : fleet.getFleet()) {
                if (airplane.getIsExpired().toString().equalsIgnoreCase("true")) {
                    Object row[] = new Object[4];
                    row[0] = airplane;
                    row[1] = airplane.getAirplaneModelNum();
                    row[2] = airplane.getAirplaneSerialNum();
                    row[3] = airplane.getAirplaneManufacturer();

                    defaultModel.addRow(row);
                }
            }
        }
        if(searchComboBox.getSelectedItem().toString().equals("Boeing Manufacturer"))
        {
                    countLabel.setVisible(false);
        labelForTimeStamp.setVisible(false);
        listForOneColumn.setVisible(false);
                    searchText.setEditable(false);


        DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();
        defaultModel.setRowCount(0);
        for (Airplane airplane : fleet.getFleet()) {
            if (airplane.getAirplaneManufacturer().equalsIgnoreCase("Boeing")) {
                Object row[] = new Object[4];
                row[0] = airplane;
                row[1] = airplane.getAirplaneModelNum();
                row[2] = airplane.getAirplaneSerialNum();
                row[3] = airplane.getAirplaneManufacturer();

                defaultModel.addRow(row);
            }
        }
        }
        if(searchComboBox.getSelectedItem().toString().equals("Airplane Availability"))
        {
             labelForTimeStamp.setVisible(false);
        listForOneColumn.setVisible(true);
        listForOneColumn.setEnabled(true);
        /* int count = 0;
        //Hide the other columns other than airplane name
        DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();

        TableColumn manufacturerColumn = airplaneTableForSearch.getColumnModel().getColumn(3);
        airplaneTableForSearch.getColumnModel().removeColumn(manufacturerColumn);
        TableColumn modelNumColumn = airplaneTableForSearch.getColumnModel().getColumn(2);
        airplaneTableForSearch.getColumnModel().removeColumn(modelNumColumn);

        TableColumn serialNumColumn = airplaneTableForSearch.getColumnModel().getColumn(1);
        airplaneTableForSearch.getColumnModel().removeColumn(serialNumColumn);
        defaultModel.setRowCount(0);
        for (Airplane airplane : fleet.getFleet()) {

            if (airplane.getIsAvailable().toString().equalsIgnoreCase("true")) {
                count++;
                Object row[] = new Object[1];
                row[0] = airplane;

                defaultModel.addRow(row);
                countLabel.setVisible(true);
                countLabel.setText("Airplanes Available : " + count);
            }
        }*/
        DefaultListModel<String> dlm = new DefaultListModel<String>();
        ArrayList<String> airplaneManufacture = new ArrayList<String>();
        for (Airplane airplane : fleet.getFleet()) {
            if (airplane.getIsAvailable().toString().equalsIgnoreCase("true")) {
                airplaneManufacture.add(airplane.getAirplaneName());
            }
        }
        Set<String> hs = new HashSet<>();
        hs.addAll(airplaneManufacture);
        airplaneManufacture.clear();
        airplaneManufacture.addAll(hs);
        for (int i = 0; i < airplaneManufacture.size(); i++) {
            dlm.addElement(airplaneManufacture.get(i));
        }
        JList<String> list = new JList<>(dlm);
        listForOneColumn.setModel(dlm);

        }
                if(searchComboBox.getSelectedItem().toString().equals("First Available Airplane"))
                {
                    listForOneColumn.setVisible(false);

        DateFormat dateFormat = new SimpleDateFormat("MM/dd/YYYY");
        Date date = new Date();
        // System.out.println(dateFormat.format(date));
        countLabel.setVisible(false);
        labelForTimeStamp.setVisible(false);
        DefaultTableModel defaultModel = (DefaultTableModel) airplaneTableForSearch.getModel();
        defaultModel.setRowCount(0);
        Date[] dates = new Date[40];
        Integer[] daysBetween = new Integer[20];
        int i = 0, small = 0, j = 1;
        long minDiff = -1,
                currentTime = date.getTime();
        Date minDate = null;
        for (Airplane airplane : fleet.getFleet()) {

            dates[i] = airplane.getAvailabityDate();
            // System.out.println(date);
            //System.out.println(dates[i]);
            long diff = Math.abs(currentTime - dates[i].getTime());
            if ((minDiff == -1) || (diff < minDiff)) {
                minDiff = diff;
                minDate = dates[i];
            }

            /*if (dateFormat.format(dates[i]).contains("2017")) {
                Calendar day1 = Calendar.getInstance();
                Calendar day2 = Calendar.getInstance();
                day1.setTime(dates[i]);
                day2.setTime(date);
                daysBetween[i] = day1.get(Calendar.DAY_OF_YEAR) - day2.get(Calendar.DAY_OF_YEAR);
                System.out.println(daysBetween[i]+"And the date is" +dates[i]);
               
             */
            i++;

            // }
        }
        // System.out.println("Minimum Date "+minDate);
        for (Airplane airplane : fleet.getFleet()) {
            if (airplane.getAvailabityDate().equals(minDate)) {
                Object row[] = new Object[4];
                row[0] = airplane;
                row[1] = airplane.getAirplaneModelNum();
                row[2] = airplane.getAirplaneSerialNum();
                row[3] = airplane.getAirplaneManufacturer();

                defaultModel.addRow(row);
            }
        }
                    
                }
                if(searchComboBox.getSelectedItem().toString().equals("Manufacturers of the Airline"))
                {
                      listForOneColumn.setVisible(true);
        listForOneColumn.setEnabled(true);
        DefaultListModel<String> dlm = new DefaultListModel<String>();
        ArrayList<String> airplaneManufacture = new ArrayList<String>();
        for (Airplane airplane : fleet.getFleet()) {
            airplaneManufacture.add(airplane.getAirplaneManufacturer());
        }
        Set<String> hs = new HashSet<>();
        hs.addAll(airplaneManufacture);
        airplaneManufacture.clear();
        airplaneManufacture.addAll(hs);
        for (int i = 0; i < airplaneManufacture.size(); i++) {
            dlm.addElement(airplaneManufacture.get(i));
        }
        JList<String> list = new JList<>(dlm);
        listForOneColumn.setModel(dlm);
                }
    }

    private void setVisibleFalse() {
        //set the Text fields false
        nameTextField.setVisible(false);
        manufacturerTextField.setVisible(false);
        manufactureDateTxt.setVisible(false);
        manufacturerTextField.setVisible(false);
        seatsTextField.setVisible(false);
        serialNumTextField.setVisible(false);
        modelTextField.setVisible(false);
        isAvailableTextField.setVisible(false);
        certificateStatusText.setVisible(false);
        airportTextField.setVisible(false);
        avaiDateTextField.setVisible(false);
        // set the label feilds as false
        nameLabel.setVisible(false);
        labelForManufacturer.setVisible(false);
        seatsLabel.setVisible(false);
        serialNumLabel.setVisible(false);
        modelNumLabel.setVisible(false);
        manuDateLabel.setVisible(false);
        avaiStatusLabel.setVisible(false);
        certiLabel.setVisible(false);
        airportLabel.setVisible(false);
        avaiLabel.setVisible(false);
        listForOneColumn.setVisible(false);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airplaneTableForSearch;
    private javax.swing.JComboBox<String> airportComboBox;
    private javax.swing.JLabel airportLabel;
    private javax.swing.JTextField airportTextField;
    private javax.swing.JTextField avaiDateTextField;
    private javax.swing.JLabel avaiLabel;
    private javax.swing.JButton avaiStatusButton1;
    private javax.swing.JLabel avaiStatusLabel;
    private javax.swing.JLabel certiLabel;
    private javax.swing.JTextField certificateStatusText;
    private javax.swing.JLabel countLabel;
    private javax.swing.JTextField isAvailableTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel labelForManufacturer;
    private javax.swing.JLabel labelForTimeStamp;
    private javax.swing.JList<String> listForOneColumn;
    private javax.swing.JLabel manuDateLabel;
    private javax.swing.JTextField manufactureDateTxt;
    private javax.swing.JTextField manufacturerTextField;
    private javax.swing.JTextField maxSeatTextField;
    private javax.swing.JTextField minSeatTextBox;
    private javax.swing.JLabel modelNumLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JComboBox<String> searchComboBox;
    private javax.swing.JTextField searchText;
    private javax.swing.JButton seatSearch;
    private javax.swing.JLabel seatsLabel;
    private javax.swing.JTextField seatsTextField;
    private javax.swing.JLabel seatsearchLabel;
    private javax.swing.JLabel serialNumLabel;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton timeStampButton;
    // End of variables declaration//GEN-END:variables

    private void setVisibleTrue() {
        //set the Text fields true
        nameTextField.setVisible(true);
        manufacturerTextField.setVisible(true);
        manufactureDateTxt.setVisible(true);
        manufacturerTextField.setVisible(true);
        seatsTextField.setVisible(true);
        serialNumTextField.setVisible(true);
        modelTextField.setVisible(true);
        isAvailableTextField.setVisible(true);
        certificateStatusText.setVisible(true);
        airportTextField.setVisible(true);
        avaiDateTextField.setVisible(true);
        listForOneColumn.setVisible(true);
        // set the label feilds as true
        nameLabel.setVisible(true);
        labelForManufacturer.setVisible(true);
        seatsLabel.setVisible(true);
        serialNumLabel.setVisible(true);
        modelNumLabel.setVisible(true);
        manuDateLabel.setVisible(true);
        avaiStatusLabel.setVisible(true);
        certiLabel.setVisible(true);
        airportLabel.setVisible(true);
        avaiLabel.setVisible(true);
    }

}
