/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfacePackage;

import BusinessPackage.Airplane;
import BusinessPackage.Fleet;
import java.sql.Timestamp;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ragha
 */
public class ViewAirplaneJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewAirplaneJPanel
     */
    private Fleet fleet;
    Timestamp timestamp;
    ViewAirplaneJPanel viewAirplaneJPanel;
    public ViewAirplaneJPanel(Fleet fleet) {
        initComponents();
        this.fleet = fleet;
        populateTable();
    }

    public Timestamp getTimestamp() {
        return timestamp;
    }
    public void setTimestamp(Timestamp timestamp)
    {
        this.timestamp = timestamp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        manufacturerTextField = new javax.swing.JTextField();
        seatsTextField = new javax.swing.JTextField();
        serialNumTextField = new javax.swing.JTextField();
        modelTextField = new javax.swing.JTextField();
        manufactureDateTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplaneTable1 = new javax.swing.JTable();
        viewAirplaneDetailsButton = new javax.swing.JButton();
        updateAirplaneButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        isAvailableTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        certificateStatusText = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        nameTextField = new javax.swing.JTextField();
        submitUpdateButton = new javax.swing.JButton();
        labelForTimestamp = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Manufacturer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 542, -1, -1));

        jLabel2.setText("No of seats");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 602, -1, -1));

        jLabel3.setText("Serial Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 662, -1, -1));

        jLabel4.setText("Model Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 722, -1, -1));

        jLabel5.setText("Manufacture Date");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 782, -1, -1));

        manufacturerTextField.setEnabled(false);
        add(manufacturerTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 532, 280, -1));

        seatsTextField.setEnabled(false);
        add(seatsTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 592, 280, -1));

        serialNumTextField.setEnabled(false);
        add(serialNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 652, 280, -1));

        modelTextField.setEnabled(false);
        add(modelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 712, 280, -1));

        manufactureDateTxt.setEnabled(false);
        add(manufactureDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 779, 280, -1));

        airplaneTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airplane Name", "Model Number", "Serial Number", "Manufacturer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(airplaneTable1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 0, 704, 421));

        viewAirplaneDetailsButton.setText("View");
        viewAirplaneDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirplaneDetailsButtonActionPerformed(evt);
            }
        });
        add(viewAirplaneDetailsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 101, 83, -1));

        updateAirplaneButton.setText("Update");
        updateAirplaneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateAirplaneButtonActionPerformed(evt);
            }
        });
        add(updateAirplaneButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(969, 172, -1, -1));

        jLabel6.setText("Availability Status");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 850, -1, -1));

        isAvailableTextField.setToolTipText("Give the Status as Either \"true\" or \"false\" ");
        isAvailableTextField.setEnabled(false);
        add(isAvailableTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 847, 280, -1));

        jLabel7.setText("Maintenance Certificate");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 908, -1, -1));

        certificateStatusText.setToolTipText("Give the value as either \"Expired\" or \"Valid\"");
        certificateStatusText.setEnabled(false);
        add(certificateStatusText, new org.netbeans.lib.awtextra.AbsoluteConstraints(524, 905, 280, -1));

        nameLabel.setText("Name");
        add(nameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, -1, -1));

        nameTextField.setEnabled(false);
        add(nameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 480, 280, -1));

        submitUpdateButton.setText("Submit after Update");
        submitUpdateButton.setEnabled(false);
        submitUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitUpdateButtonActionPerformed(evt);
            }
        });
        add(submitUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 640, -1, -1));
        add(labelForTimestamp, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 560, 360, 30));
    }// </editor-fold>//GEN-END:initComponents
private void populateTable() {
        DefaultTableModel defaultModel = (DefaultTableModel) airplaneTable1.getModel();
        defaultModel.setRowCount(0);
        for (Airplane airplane : fleet.getFleet()) {
            Object row[] = new Object[4];
            row[0] = airplane;
            row[1] = airplane.getAirplaneModelNum();
            row[2] = airplane.getAirplaneSerialNum();
            row[3] = airplane.getAirplaneManufacturer();

            defaultModel.addRow(row);
        }
    }
    private void viewAirplaneDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirplaneDetailsButtonActionPerformed
       labelForTimestamp.setVisible(false);
        int selectedRow = airplaneTable1.getSelectedRow();
        if (selectedRow >= 0) {
            Airplane airplane = (Airplane) airplaneTable1.getValueAt((Integer) selectedRow, 0);
            nameTextField.setText(airplane.getAirplaneName());
            manufactureDateTxt.setText(String.valueOf(airplane.getAirplaneManufactureDate()));
            manufacturerTextField.setText(airplane.getAirplaneManufacturer());
            seatsTextField.setText(Integer.toString(airplane.getAirplaneSeats()));
            serialNumTextField.setText(airplane.getAirplaneSerialNum());
            modelTextField.setText(airplane.getAirplaneModelNum());
            isAvailableTextField.setText(airplane.getIsAvailable().toString());
            if ((airplane.getIsExpired().toString()).equalsIgnoreCase("true")) {
                certificateStatusText.setText("Expired");
            } else {
                certificateStatusText.setText("Valid");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
    }//GEN-LAST:event_viewAirplaneDetailsButtonActionPerformed

    private void updateAirplaneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateAirplaneButtonActionPerformed
               labelForTimestamp.setVisible(true);

        enableAlltheTextFields();


    }//GEN-LAST:event_updateAirplaneButtonActionPerformed

    private void submitUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitUpdateButtonActionPerformed
       labelForTimestamp.setVisible(true);

        int selectedRow = airplaneTable1.getSelectedRow();
        if (selectedRow >= 0) {
            Airplane airplane = (Airplane) airplaneTable1.getValueAt(selectedRow, 0);
            DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
            try {
                airplane.setAirplaneManufactureDate(df.parse(manufactureDateTxt.getText()));
            } catch (ParseException ex) {
                Logger.getLogger(CreateAirplaneJPanel.class.getName()).log(Level.SEVERE, null, ex);

            }
            airplane.setAirplaneName(nameTextField.getText());
            airplane.setAirplaneManufacturer(manufacturerTextField.getText());
            airplane.setAirplaneModelNum(modelTextField.getText());
            airplane.setAirplaneSeats(Integer.parseInt(seatsTextField.getText()));
            airplane.setAirplaneSerialNum(serialNumTextField.getText());
            airplane.setIsAvailable(Boolean.getBoolean(isAvailableTextField.getText()));
            airplane.setIsExpired(Boolean.valueOf(certificateStatusText.getText()));
            populateTable();

            nameTextField.setText("");
            manufacturerTextField.setText("");
            modelTextField.setText("");
            seatsTextField.setText("");
            serialNumTextField.setText("");
            manufactureDateTxt.setText("");
            isAvailableTextField.setText("");
            certificateStatusText.setText("");
 viewAirplaneJPanel= new ViewAirplaneJPanel(fleet);
        viewAirplaneJPanel.setTimestamp(new Timestamp(System.currentTimeMillis()));
        airplane.setTimestamp(viewAirplaneJPanel.getTimestamp());
        labelForTimestamp.setText("Catalog Last Updated on: " + viewAirplaneJPanel.getTimestamp().toString());
        } else {
            JOptionPane.showMessageDialog(null, "Please select any row");
        }
      
        JOptionPane.showMessageDialog(null, "Airplane Entry Updated");
    }//GEN-LAST:event_submitUpdateButtonActionPerformed

    private void enableAlltheTextFields() {
        nameTextField.setEnabled(true);

        manufacturerTextField.setEnabled(true);
        manufactureDateTxt.setEnabled(true);
        manufacturerTextField.setEnabled(true);
        seatsTextField.setEnabled(true);
        serialNumTextField.setEnabled(true);
        modelTextField.setEnabled(true);
        isAvailableTextField.setEnabled(true);
        certificateStatusText.setEnabled(true);
        submitUpdateButton.setEnabled(true);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airplaneTable1;
    private javax.swing.JTextField certificateStatusText;
    private javax.swing.JTextField isAvailableTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelForTimestamp;
    private javax.swing.JTextField manufactureDateTxt;
    private javax.swing.JTextField manufacturerTextField;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField nameTextField;
    private javax.swing.JTextField seatsTextField;
    private javax.swing.JTextField serialNumTextField;
    private javax.swing.JButton submitUpdateButton;
    private javax.swing.JButton updateAirplaneButton;
    private javax.swing.JButton viewAirplaneDetailsButton;
    // End of variables declaration//GEN-END:variables

}
