/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageFlights;

import Business.Airline;
import Business.Fleet;
import Business.Flight;
import Business.Seat;
import Business.TravelAgency;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;

/**
 *
 * @author ragha
 */
public class CreateFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateFlightJPanel
     */
    private JPanel userContainer;
    private TravelAgency airlineDirectory;
    ArrayList<String> airlineNameList = new ArrayList<String>();

    public CreateFlightJPanel(JPanel userContainer, TravelAgency airlineDirectory) {
        initComponents();
        this.userContainer = userContainer;
        this.airlineDirectory = airlineDirectory;
        for (Airline airline : airlineDirectory.getTravelAgency()) {
            airlineNameList.add(airline.getName());
        }
        airlineComboBox.setModel(new DefaultComboBoxModel(airlineNameList.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        flightNameText = new javax.swing.JTextField();
        flightNumText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        submitFlightButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        airlineComboBox = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sourceText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        destText = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        deptTimeText = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        arrivalTimeText = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        flightPriceText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        maxSeatsText = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setBorder(new javax.swing.border.MatteBorder(null));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Flight Creation");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        flightNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightNameTextActionPerformed(evt);
            }
        });
        add(flightNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 170, -1));

        flightNumText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flightNumTextActionPerformed(evt);
            }
        });
        add(flightNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 170, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Flight Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Flight Serial Number");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Airline Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        submitFlightButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        submitFlightButton.setText("Submit");
        submitFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFlightButtonActionPerformed(evt);
            }
        });
        add(submitFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 550, -1, -1));

        backButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        add(airlineComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 170, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Destination");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 150, -1));

        sourceText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourceTextActionPerformed(evt);
            }
        });
        add(sourceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, 170, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Source");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 150, -1));

        destText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destTextActionPerformed(evt);
            }
        });
        add(destText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 170, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Departure Date");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, -1, -1));
        add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Maximum Seats");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, -1, -1));
        add(deptTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 170, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Departure Time");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, -1));
        add(arrivalTimeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 170, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Arrival Time");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, -1, -1));
        add(flightPriceText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 170, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Price");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 450, -1, -1));
        add(maxSeatsText, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 490, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void flightNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightNameTextActionPerformed

    private void flightNumTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flightNumTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flightNumTextActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Go to the previous page
        userContainer.remove(this);
        Component[] componentArray = userContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlightJPanel manageFlightJPanel = (ManageFlightJPanel) component;
        manageFlightJPanel.populateTable();
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitFlightButtonActionPerformed
        // TODO add your handling code here:
        Airline airline = airlineDirectory.searchAirline(airlineComboBox.getSelectedItem().toString());
        Fleet fleet = airline.getFleet();
        Flight flight = fleet.addAirplane();
        flight.setFlightName(flightNameText.getText());
        flight.setFlightSerialNum(flightNumText.getText());
        flight.setAirlineName(airlineComboBox.getSelectedItem().toString());
        flight.setDestination(destText.getText());
        flight.setSource(sourceText.getText());
        flight.setDepartureDate(jDateChooser1.getDate());
        flight.setPrice(Integer.parseInt(flightPriceText.getText()));
        
        flight.setDeptTime(LocalTime.parse(deptTimeText.getText()));
        flight.setArrivalTime(LocalTime.parse(arrivalTimeText.getText()));
        Seat seat = new Seat();
        seat.setFlightName(flight.getFlightSerialNum());
        seat.setNumOfSeats(Integer.parseInt(maxSeatsText.getText()));
        flight.setSeat(seat);

    }//GEN-LAST:event_submitFlightButtonActionPerformed
   
    private void sourceTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourceTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourceTextActionPerformed

    private void destTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> airlineComboBox;
    private javax.swing.JTextField arrivalTimeText;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField deptTimeText;
    private javax.swing.JTextField destText;
    private javax.swing.JTextField flightNameText;
    private javax.swing.JTextField flightNumText;
    private javax.swing.JTextField flightPriceText;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField maxSeatsText;
    private javax.swing.JTextField sourceText;
    private javax.swing.JButton submitFlightButton;
    // End of variables declaration//GEN-END:variables
}
