/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageFlights;

import Business.Airline;
import Business.Flight;
import Business.TravelAgency;
import UserInterface_ManageAirline.ViewAirlinerJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ragha
 */
public class ManageFlightJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFlightJPanel
     */
    TravelAgency airlineDirectory;
    JPanel userContainer;
    public ManageFlightJPanel(JPanel userContainer,TravelAgency airlineDirectory) {
        this.airlineDirectory = airlineDirectory;
        this.userContainer = userContainer;
        initComponents();
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFlight = new javax.swing.JTable();
        newAirlinerButton = new javax.swing.JButton();
        viewAirlinerButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tableFlight.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Name", "Airliner"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableFlight);

        newAirlinerButton.setText("New Flight <<");
        newAirlinerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newAirlinerButtonActionPerformed(evt);
            }
        });

        viewAirlinerButton.setText("View Flight <<");
        viewAirlinerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAirlinerButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Manage Airlines");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewAirlinerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newAirlinerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(214, 214, 214)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(newAirlinerButton)
                .addGap(27, 27, 27)
                .addComponent(viewAirlinerButton)
                .addGap(73, 73, 73))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newAirlinerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newAirlinerButtonActionPerformed
        // Call the create Airline Jpanel to create Airlines
        CreateFlightJPanel createFlightJPanel = new CreateFlightJPanel(userContainer,airlineDirectory);
        userContainer.add("CreateFlightJPanel", createFlightJPanel);
        CardLayout cardLayout = (CardLayout) userContainer.getLayout();
        cardLayout.next(userContainer);

    }//GEN-LAST:event_newAirlinerButtonActionPerformed

    private void viewAirlinerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAirlinerButtonActionPerformed
        // View Airline Directory
    /*    int selectedRows = tableFlight.getSelectedRow();
        if (selectedRows < 0) {
            JOptionPane.showMessageDialog(null, "Select any row from the table to view the details", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            Airline airline = (Airline) tableFlight.getValueAt(selectedRows, 0);
            ViewFlightJPanel viewFlightJPanel = new ViewFlightJPanel(userContainer, airline);
            userContainer.add("ViewFlightJPanel", viewFlightJPanel);
            CardLayout cardLayout = (CardLayout) userContainer.getLayout();
            cardLayout.next(userContainer);

        }*/
    }//GEN-LAST:event_viewAirlinerButtonActionPerformed

public void populateTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableFlight.getModel();
        defaultTableModel.setRowCount(0);
      
            for (Airline airline : airlineDirectory.getTravelAgency()) {
                {
                    for (Flight f : airline.getFleet().getFleet())
                    {
                         Object[] row = new Object[2];
            row[0] = f;
            row[1] = airline.getName();
            
            defaultTableModel.addRow(row);
                        
                    }
                }
            }
            
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newAirlinerButton;
    private javax.swing.JTable tableFlight;
    private javax.swing.JButton viewAirlinerButton;
    // End of variables declaration//GEN-END:variables
}
