/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HRRole;

import Business.Business;
import Business.Person;
import Business.UserAccount;
import UserInterface.AdminRole.SearchUserAccountJPanel;
import UserInterface.AdminRole.UpdateUserAccountJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ragha
 */
public class ManagePersonDirectoryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePersonDirectoryJPanel
     */
    private JPanel userContainer;
    private Business b;

    public ManagePersonDirectoryJPanel(JPanel userContainer, Business b) {
        initComponents();
        this.userContainer = userContainer;
        this.b = b;
        populateTable();
    }

    public void populateTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) personTable.getModel();
        defaultTableModel.setRowCount(0);

        for (Person person : b.getPersonDir().getPersonDir()) 
            {
                if(person.getUserAccount().isEmpty())
                {
                    Object[] row = new Object[4];
                    row[0] = person;
                    row[1] = person.getFirstName();
                    row[2] = person.getLastName();
                    row[3] = "-----";
                    defaultTableModel.addRow(row);
                }
                for (UserAccount ua : person.getUserAccount()) {
                    Object[] row = new Object[4];
                    row[0] = person;
                    row[1] = person.getFirstName();
                    row[2] = person.getLastName();
                    row[3] = ua;
                    defaultTableModel.addRow(row);

                }
            }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        personTable = new javax.swing.JTable();
        findPerson = new javax.swing.JButton();
        newPersonButton = new javax.swing.JButton();
        updatePersonButton = new javax.swing.JButton();

        personTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "FirstName", "LastName", "user name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(personTable);

        findPerson.setText("Find Person >>");
        findPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findPersonActionPerformed(evt);
            }
        });

        newPersonButton.setText("New Person >>");
        newPersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPersonButtonActionPerformed(evt);
            }
        });

        updatePersonButton.setText("Update Person >>");
        updatePersonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePersonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(findPerson, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 763, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newPersonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatePersonButton, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(findPerson))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(76, 76, 76)
                .addComponent(newPersonButton)
                .addGap(21, 21, 21)
                .addComponent(updatePersonButton)
                .addContainerGap(253, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void newPersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPersonButtonActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel createPersonJPanel = new CreatePersonJPanel(userContainer, b);
        userContainer.add("CreatePersonJPanel", createPersonJPanel);
        CardLayout cardLayout = (CardLayout) userContainer.getLayout();
        cardLayout.next(userContainer);
    }//GEN-LAST:event_newPersonButtonActionPerformed

    private void updatePersonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePersonButtonActionPerformed
        // TODO add your handling code here:
          int selectedRows = personTable.getSelectedRow();
        if (selectedRows < 0) {
            JOptionPane.showMessageDialog(null, "Select any row from the table to view the details", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            Person person = (Person) personTable.getValueAt(selectedRows, 0);
            UpdatePersonJPanel updatePersonJPanel = new UpdatePersonJPanel(userContainer, person);
            userContainer.add("UpdatePersonJPanel", updatePersonJPanel);
            CardLayout cardLayout = (CardLayout) userContainer.getLayout();
            cardLayout.next(userContainer);

        }
    }//GEN-LAST:event_updatePersonButtonActionPerformed

    private void findPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findPersonActionPerformed
        // TODO add your handling code here:
        SearchPersonJPanel searchPersonJPanel = new SearchPersonJPanel(userContainer, b);
        userContainer.add("SearchPersonJPanel", searchPersonJPanel);
        CardLayout cardLayout = (CardLayout) userContainer.getLayout();
        cardLayout.next(userContainer);
                                  
    }//GEN-LAST:event_findPersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton findPerson;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newPersonButton;
    private javax.swing.JTable personTable;
    private javax.swing.JButton updatePersonButton;
    // End of variables declaration//GEN-END:variables
}
