/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIPackage;

import BusinessPackage.Address;
import BusinessPackage.CreditCard;
import BusinessPackage.FinancialAccounts;
import BusinessPackage.LicenseData;
import BusinessPackage.Person;
import BusinessPackage.Spouse;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author ragha
 */
public class CreateSpouseProfileJForm extends javax.swing.JPanel {

    /**
     * Creates new form CreateProfileJForm
     */
    private Person person;
    private Address address;
    private LicenseData licenseData;
    private CreditCard creditCard;
    private FinancialAccounts finAccounts;
    public CreateSpouseProfileJForm(Person person, Address address,LicenseData licenseData, CreditCard creditCard, FinancialAccounts financialAccounts) {
        initComponents();
      
        buttonGroupForGender.add(maleRadioButton);
        buttonGroupForGender.add(femaleRadioButton);
        this.person = person;
        this.address = address;
        this.licenseData = licenseData;
        this.creditCard = creditCard;
        this.finAccounts = financialAccounts;
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupForMaritalStatus = new javax.swing.ButtonGroup();
        buttonGroupForGender = new javax.swing.ButtonGroup();
        headerForCreate = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        firstNameLabel1 = new javax.swing.JLabel();
        emailID = new javax.swing.JLabel();
        lastNameLabel1 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        firstNameTextField1 = new javax.swing.JTextField();
        phoneNumberTextField = new javax.swing.JTextField();
        emailIDTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pincodeTextField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        streetNameTextField2 = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        cityTextField1 = new javax.swing.JTextField();
        submitButton1 = new javax.swing.JButton();
        photoLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        attachButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        licenseNumLabel = new javax.swing.JLabel();
        licenseNumTextField = new javax.swing.JTextField();
        licenseDOILabel = new javax.swing.JLabel();
        licenseDOITextField = new javax.swing.JTextField();
        licenseExpiryLabel = new javax.swing.JLabel();
        ExpiryDateTextField = new javax.swing.JTextField();
        licenseClassLabel = new javax.swing.JLabel();
        licenseClassTextField = new javax.swing.JTextField();
        licensePlaceOfIssueLabel = new javax.swing.JLabel();
        licensePlaceTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        creditCardNameLabel = new javax.swing.JLabel();
        creditPlaceTxtField = new javax.swing.JTextField();
        issuancePlaceLabel = new javax.swing.JLabel();
        creditNumTxtField1 = new javax.swing.JTextField();
        creditCardDOE1 = new javax.swing.JLabel();
        creditDOETxtField1 = new javax.swing.JTextField();
        bankLabel = new javax.swing.JLabel();
        bankTxtField = new javax.swing.JTextField();
        creditCardDOI = new javax.swing.JLabel();
        creditDOITxtField = new javax.swing.JTextField();
        financialLabel = new javax.swing.JLabel();
        savingsRadioButton = new javax.swing.JRadioButton();
        checkingRadioButton = new javax.swing.JRadioButton();
        accountStatusLabel = new javax.swing.JLabel();
        accountStatusCombo = new javax.swing.JComboBox<>();
        accountLabel2 = new javax.swing.JLabel();
        accountLabel3 = new javax.swing.JLabel();
        creationDateAccountTxt = new javax.swing.JTextField();
        accountLabel4 = new javax.swing.JLabel();
        secHolderTxtField = new javax.swing.JTextField();
        accountStatusLabel1 = new javax.swing.JLabel();
        sAccountStatusCombo = new javax.swing.JComboBox<>();
        accountLabel5 = new javax.swing.JLabel();
        sAccCreationDateAccountTxt = new javax.swing.JTextField();
        accountLabel7 = new javax.swing.JLabel();
        sAccSecHolderTxtField = new javax.swing.JTextField();
        sCreditAmtTextField = new javax.swing.JTextField();
        accountLabel6 = new javax.swing.JLabel();
        debtAmtTextField1 = new javax.swing.JTextField();
        accountLabel8 = new javax.swing.JLabel();
        sDebtAmtTextField1 = new javax.swing.JTextField();
        accountLabel9 = new javax.swing.JLabel();
        cCreditAmtTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lastNameLabel2 = new javax.swing.JLabel();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        dobTextField2 = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerForCreate.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        headerForCreate.setForeground(new java.awt.Color(0, 51, 102));
        headerForCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerForCreate.setText("Fill in your Details");
        headerForCreate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add(headerForCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 388, -1));
        headerForCreate.getAccessibleContext().setAccessibleDescription("");

        lastNameLabel.setText("Last Name");
        add(lastNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 143, 26));

        firstNameLabel1.setText("First Name");
        add(firstNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 143, 26));

        emailID.setText("Email ID");
        add(emailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 143, 26));

        lastNameLabel1.setText("Gender");
        add(lastNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 143, 26));

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 143, -1));

        firstNameTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextField1ActionPerformed(evt);
            }
        });
        add(firstNameTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 143, -1));

        phoneNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextFieldActionPerformed(evt);
            }
        });
        add(phoneNumberTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 143, -1));

        emailIDTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIDTextField2ActionPerformed(evt);
            }
        });
        add(emailIDTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 143, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Address");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 143, 26));

        jLabel2.setText("Street Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel3.setText("City");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel4.setText("State");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel5.setText("Country");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jLabel6.setText("Pin Code");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        pincodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincodeTextFieldActionPerformed(evt);
            }
        });
        add(pincodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 610, 143, -1));

        stateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextFieldActionPerformed(evt);
            }
        });
        add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 143, -1));

        streetNameTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameTextField2ActionPerformed(evt);
            }
        });
        add(streetNameTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 143, -1));

        countryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextFieldActionPerformed(evt);
            }
        });
        add(countryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 143, -1));

        cityTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextField1ActionPerformed(evt);
            }
        });
        add(cityTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 143, -1));

        submitButton1.setText("Submit");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });
        add(submitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 710, -1, -1));

        photoLabel.setText("         Your Photo");
        photoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(photoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 80, 181, 163));

        pathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextFieldActionPerformed(evt);
            }
        });
        add(pathTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 250, 239, -1));

        attachButton.setText("Attach");
        attachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButtonActionPerformed(evt);
            }
        });
        add(attachButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("License Data");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        licenseNumLabel.setText("License Number");
        add(licenseNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        licenseNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumTextFieldActionPerformed(evt);
            }
        });
        add(licenseNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 143, -1));

        licenseDOILabel.setText("Date of Issue");
        add(licenseDOILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        licenseDOITextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseDOITextFieldActionPerformed(evt);
            }
        });
        add(licenseDOITextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 143, -1));

        licenseExpiryLabel.setText("Expiry Date");
        add(licenseExpiryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        ExpiryDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpiryDateTextFieldActionPerformed(evt);
            }
        });
        add(ExpiryDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 143, -1));

        licenseClassLabel.setText("Class");
        add(licenseClassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        licenseClassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseClassTextFieldActionPerformed(evt);
            }
        });
        add(licenseClassTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 143, -1));

        licensePlaceOfIssueLabel.setText("Place Of Issuance");
        add(licensePlaceOfIssueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        licensePlaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licensePlaceTextFieldActionPerformed(evt);
            }
        });
        add(licensePlaceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 143, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Credit Card");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, -1, -1));

        creditCardNameLabel.setText("Credit Card Number ");
        add(creditCardNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));
        add(creditPlaceTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 143, -1));

        issuancePlaceLabel.setText("Issuance Place");
        add(issuancePlaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, -1));
        add(creditNumTxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 143, -1));

        creditCardDOE1.setText("Credit Card Expiry");
        add(creditCardDOE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));
        add(creditDOETxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 143, -1));

        bankLabel.setText("Bank");
        add(bankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));
        add(bankTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 143, -1));

        creditCardDOI.setText("Issue Date");
        add(creditCardDOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, -1));
        add(creditDOITxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 143, -1));

        financialLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        financialLabel.setText("Financial Accounts Section");
        add(financialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        savingsRadioButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        savingsRadioButton.setText("Savings Account");
        savingsRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                savingsRadioButtonStateChanged(evt);
            }
        });
        savingsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsRadioButtonActionPerformed(evt);
            }
        });
        add(savingsRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        checkingRadioButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkingRadioButton.setText("Checkings Account");
        checkingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingRadioButtonActionPerformed(evt);
            }
        });
        add(checkingRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, -1, -1));

        accountStatusLabel.setText("Status");
        add(accountStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, -1, -1));

        accountStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Not Active" }));
        accountStatusCombo.setEnabled(false);
        add(accountStatusCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 440, -1, -1));

        accountLabel2.setText("Secondary Holder");
        add(accountLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 530, -1, -1));

        accountLabel3.setText("Debt Amount");
        add(accountLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, -1, -1));

        creationDateAccountTxt.setEnabled(false);
        add(creationDateAccountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 560, 143, -1));

        accountLabel4.setText("Creation Date");
        add(accountLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 570, -1, -1));

        secHolderTxtField.setEnabled(false);
        add(secHolderTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 520, 143, -1));

        accountStatusLabel1.setText("Status");
        add(accountStatusLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        sAccountStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Not Active" }));
        sAccountStatusCombo.setEnabled(false);
        add(sAccountStatusCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        accountLabel5.setText("Secondary Holder");
        add(accountLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        sAccCreationDateAccountTxt.setEnabled(false);
        add(sAccCreationDateAccountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 143, -1));

        accountLabel7.setText("Creation Date");
        add(accountLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, -1));

        sAccSecHolderTxtField.setEnabled(false);
        add(sAccSecHolderTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 143, -1));

        sCreditAmtTextField.setEnabled(false);
        add(sCreditAmtTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, 143, -1));

        accountLabel6.setText("Credit Amount");
        add(accountLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 610, -1, -1));

        debtAmtTextField1.setEnabled(false);
        add(debtAmtTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 480, 143, -1));

        accountLabel8.setText("Debt Amount");
        add(accountLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, -1, -1));

        sDebtAmtTextField1.setEnabled(false);
        add(sDebtAmtTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 143, -1));

        accountLabel9.setText("Credit Amount");
        add(accountLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, -1, -1));

        cCreditAmtTextField1.setEnabled(false);
        add(cCreditAmtTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 600, 143, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Basic Info");
        jLabel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lastNameLabel2.setText("Date Of Birth");
        add(lastNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 143, 26));

        maleRadioButton.setText("Male");
        add(maleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        femaleRadioButton.setText("Female");
        add(femaleRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 30));

        jLabel10.setText("Phone Number");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        dobTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextField2ActionPerformed(evt);
            }
        });
        add(dobTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 143, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void attachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        pathTextField.setText(filename);
        BufferedImage image;
        try {
            image = ImageIO.read(file);
            Image resizedImg = image.getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(),
                Image.SCALE_SMOOTH);
            photoLabel.setIcon(new ImageIcon(resizedImg));
            person.setPicture(image);
        } catch (IOException ex) {
            Logger.getLogger(CreateSpouseProfileJForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_attachButtonActionPerformed

    private void licensePlaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licensePlaceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licensePlaceTextFieldActionPerformed

    private void licenseClassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseClassTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseClassTextFieldActionPerformed

    private void ExpiryDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpiryDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpiryDateTextFieldActionPerformed

    private void licenseDOITextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseDOITextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseDOITextFieldActionPerformed

    private void licenseNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumTextFieldActionPerformed

    private void pathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextFieldActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
        person.setFirstName(firstNameTextField1.getText());
        person.setLastName(lastNameTextField.getText());
        person.setEmailID(emailIDTextField2.getText());
       // person.setDate(dobTextField2.getText());
        person.setPhoneNum(phoneNumberTextField.getText());
        if(maleRadioButton.isEnabled())
        {
        person.setGenderValue("Male");
        }
        else
        {
            person.setGenderValue("Female");
        }
//        address.setCityName(cityTextField1.getText());
//        address.setStreetName(streetNameTextField2.getText());
//        address.setStateName(stateTextField.getText());
//        address.setPinCode(pincodeTextField.getText());
//        address.setCountryName(countryTextField.getText());
//        person.setAddress(address);
//        licenseData.setDateOfIssuance(licenseDOITextField.getText());
//        licenseData.setTypeOfClass(licenseClassTextField.getText());
//        licenseData.setLicenseExpDate(ExpiryDateTextField.getText());
//        licenseData.setPlaceOfIssuance(licensePlaceTextField.getText());
//        licenseData.setLicenseNum(licenseNumTextField.getText());
//        person.setLicenseData(licenseData);
//        creditCard.setCreditBank(bankTxtField.getText());
// //       creditCard.setCreditExpiry(creditDOETxtField1.getText());
////        creditCard.setCreditIssueDate(creditDOITxtField.getText());
//        creditCard.setCreditIssuePlace(creditPlaceTxtField.getText());
//        creditCard.setCreditNum(creditNumTxtField1.getText());
//        person.setCreditCard(creditCard);
//        finAccounts.getCheckingAccount().setAccountStatus(accountStatusCombo.getSelectedItem().toString());
//        // finAccounts.getCheckingAccount().
//        finAccounts.getCheckingAccount().setAccountDate(creationDateAccountTxt.getText());
//        finAccounts.getCheckingAccount().setAccountSecHolderName(secHolderTxtField.getText());
//
//        finAccounts.getCheckingAccount().setAccountCredit(cCreditAmtTextField1.getText());
//        finAccounts.getCheckingAccount().setAccountDebt(debtAmtTextField1.getText());
//
//        //finAccounts.getSavingsAccount().setAccountDebt(sDebtAmtTextField1.getText());
//        finAccounts.getSavingsAccount().setAccountDate(sAccCreationDateAccountTxt.getText());
//        finAccounts.getSavingsAccount().setAccountSecHolderName(sAccSecHolderTxtField.getText());
//        finAccounts.getSavingsAccount().setAccountCredit(sCreditAmtTextField.getText());
//        finAccounts.getSavingsAccount().setAccountStatus(sAccountStatusCombo.getSelectedItem().toString());
//        person.setFinAccounts(finAccounts);
    }//GEN-LAST:event_submitButton1ActionPerformed

    private void cityTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextField1ActionPerformed

    private void countryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldActionPerformed

    private void phoneNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextFieldActionPerformed

    private void firstNameTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextField1ActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void streetNameTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameTextField2ActionPerformed

    private void stateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextFieldActionPerformed

    private void pincodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pincodeTextFieldActionPerformed

    private void emailIDTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIDTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIDTextField2ActionPerformed

    private void savingsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsRadioButtonActionPerformed
        // TODO add your handling code here:
        if(savingsRadioButton.isEnabled())
        {
            sAccSecHolderTxtField.setEnabled(true);
            sAccCreationDateAccountTxt.setEnabled(true);
            sAccountStatusCombo.setEnabled(true);
            sDebtAmtTextField1.setEnabled(true);
            sCreditAmtTextField.setEnabled(true);
        }
    }//GEN-LAST:event_savingsRadioButtonActionPerformed

    private void dobTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextField2ActionPerformed

    private void savingsRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_savingsRadioButtonStateChanged
        
    }//GEN-LAST:event_savingsRadioButtonStateChanged

    private void checkingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingRadioButtonActionPerformed
        // Enable only when the radio is selected
             if(checkingRadioButton.isEnabled())
        {
            secHolderTxtField.setEnabled(true);
            accountStatusCombo.setEnabled(true);
            debtAmtTextField1.setEnabled(true);
            cCreditAmtTextField1.setEnabled(true);
            creationDateAccountTxt.setEnabled(true);
        }
    }//GEN-LAST:event_checkingRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExpiryDateTextField;
    private javax.swing.JLabel accountLabel2;
    private javax.swing.JLabel accountLabel3;
    private javax.swing.JLabel accountLabel4;
    private javax.swing.JLabel accountLabel5;
    private javax.swing.JLabel accountLabel6;
    private javax.swing.JLabel accountLabel7;
    private javax.swing.JLabel accountLabel8;
    private javax.swing.JLabel accountLabel9;
    private javax.swing.JComboBox<String> accountStatusCombo;
    private javax.swing.JLabel accountStatusLabel;
    private javax.swing.JLabel accountStatusLabel1;
    private javax.swing.JButton attachButton;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JTextField bankTxtField;
    private javax.swing.ButtonGroup buttonGroupForGender;
    private javax.swing.ButtonGroup buttonGroupForMaritalStatus;
    private javax.swing.JTextField cCreditAmtTextField1;
    private javax.swing.JRadioButton checkingRadioButton;
    private javax.swing.JTextField cityTextField1;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField creationDateAccountTxt;
    private javax.swing.JLabel creditCardDOE1;
    private javax.swing.JLabel creditCardDOI;
    private javax.swing.JLabel creditCardNameLabel;
    private javax.swing.JTextField creditDOETxtField1;
    private javax.swing.JTextField creditDOITxtField;
    private javax.swing.JTextField creditNumTxtField1;
    private javax.swing.JTextField creditPlaceTxtField;
    private javax.swing.JTextField debtAmtTextField1;
    private javax.swing.JTextField dobTextField2;
    private javax.swing.JLabel emailID;
    private javax.swing.JTextField emailIDTextField2;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JLabel financialLabel;
    private javax.swing.JLabel firstNameLabel1;
    private javax.swing.JTextField firstNameTextField1;
    private javax.swing.JLabel headerForCreate;
    private javax.swing.JLabel issuancePlaceLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel lastNameLabel1;
    private javax.swing.JLabel lastNameLabel2;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel licenseClassLabel;
    private javax.swing.JTextField licenseClassTextField;
    private javax.swing.JLabel licenseDOILabel;
    private javax.swing.JTextField licenseDOITextField;
    private javax.swing.JLabel licenseExpiryLabel;
    private javax.swing.JLabel licenseNumLabel;
    private javax.swing.JTextField licenseNumTextField;
    private javax.swing.JLabel licensePlaceOfIssueLabel;
    private javax.swing.JTextField licensePlaceTextField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JTextField phoneNumberTextField;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JTextField pincodeTextField;
    private javax.swing.JTextField sAccCreationDateAccountTxt;
    private javax.swing.JTextField sAccSecHolderTxtField;
    private javax.swing.JComboBox<String> sAccountStatusCombo;
    private javax.swing.JTextField sCreditAmtTextField;
    private javax.swing.JTextField sDebtAmtTextField1;
    private javax.swing.JRadioButton savingsRadioButton;
    private javax.swing.JTextField secHolderTxtField;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField streetNameTextField2;
    private javax.swing.JButton submitButton1;
    // End of variables declaration//GEN-END:variables
}
