/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUIPackage;

import BusinessPackage.Address;
import BusinessPackage.CreditCard;
import BusinessPackage.FinancialAccounts;
import BusinessPackage.LicenseData;
import BusinessPackage.Person;
import BusinessPackage.Spouse;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

/**
 *
 * @author ragha
 */
public class CreateProfileJForm extends javax.swing.JPanel {

    /**
     * Creates new form CreateProfileJForm
     */
    private Person person, spouse;
    private Address address;
    private LicenseData licenseData,spouseLicence;
    private CreditCard creditCard,spouseCreditCard;
    private FinancialAccounts finAccounts;

    public CreateProfileJForm(Person person, Address address, LicenseData licenseData, CreditCard creditCard, FinancialAccounts financialAccounts, Person spouse,CreditCard spouseCredit,LicenseData spouseLicense) {
        initComponents();
        buttonGroupForMaritalStatus.add(singleStatus);
        buttonGroupForMaritalStatus.add(Married1);
        buttonGroupForGender.add(maleRadio);
        buttonGroupForGender.add(femaleRadioButton2);
        this.person = person;
        this.spouse = spouse;
        this.address = address;
        this.licenseData = licenseData;
        this.creditCard = creditCard;
        this.finAccounts = financialAccounts;
        this.spouseCreditCard=spouseCredit;
        this.spouseLicence=spouseLicense;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupForMaritalStatus = new javax.swing.ButtonGroup();
        buttonGroupForGender = new javax.swing.ButtonGroup();
        headerForCreate = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        photoLabel = new javax.swing.JLabel();
        pathTextField = new javax.swing.JTextField();
        attachButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        licenseNumLabel = new javax.swing.JLabel();
        licenseDOILabel = new javax.swing.JLabel();
        licenseExpiryLabel = new javax.swing.JLabel();
        licenseClassLabel = new javax.swing.JLabel();
        licensePlaceOfIssueLabel = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        creditCardNameLabel = new javax.swing.JLabel();
        issuancePlaceLabel = new javax.swing.JLabel();
        creditCardDOE1 = new javax.swing.JLabel();
        bankLabel = new javax.swing.JLabel();
        creditCardDOI = new javax.swing.JLabel();
        financialLabel = new javax.swing.JLabel();
        savingsRadioButton = new javax.swing.JRadioButton();
        checkingRadioButton = new javax.swing.JRadioButton();
        accountStatusLabel = new javax.swing.JLabel();
        accountStatusCombo = new javax.swing.JComboBox<>();
        accountLabel2 = new javax.swing.JLabel();
        accountLabel3 = new javax.swing.JLabel();
        creationDateAccountTxt = new javax.swing.JTextField();
        accountLabel4 = new javax.swing.JLabel();
        secHolderTxtField = new javax.swing.JTextField();
        accountStatusLabel1 = new javax.swing.JLabel();
        sAccountStatusCombo = new javax.swing.JComboBox<>();
        sCreditAmtTextField = new javax.swing.JTextField();
        accountLabel6 = new javax.swing.JLabel();
        debtAmtTextField1 = new javax.swing.JTextField();
        accountLabel8 = new javax.swing.JLabel();
        sDebtAmtTextField1 = new javax.swing.JTextField();
        accountLabel9 = new javax.swing.JLabel();
        cCreditAmtTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        headerForCreate1 = new javax.swing.JLabel();
        lastNameLabel4 = new javax.swing.JLabel();
        firstNameLabel3 = new javax.swing.JLabel();
        emailID2 = new javax.swing.JLabel();
        lastNameLabel5 = new javax.swing.JLabel();
        lastNameTextField = new javax.swing.JTextField();
        firstNameTextField = new javax.swing.JTextField();
        phoneNumberTextField1 = new javax.swing.JTextField();
        emailIDTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        streetNameTextField3 = new javax.swing.JTextField();
        cityTextField2 = new javax.swing.JTextField();
        photoLabel1 = new javax.swing.JLabel();
        pathTextField1 = new javax.swing.JTextField();
        attachButton1 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        licenseNumLabel2 = new javax.swing.JLabel();
        licenseDOILabel2 = new javax.swing.JLabel();
        licenseExpiryLabel2 = new javax.swing.JLabel();
        licenseClassLabel1 = new javax.swing.JLabel();
        licensePlaceOfIssueLabel1 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        creditCardNameLabel1 = new javax.swing.JLabel();
        issuancePlaceLabel1 = new javax.swing.JLabel();
        creditCardDOE2 = new javax.swing.JLabel();
        bankLabel1 = new javax.swing.JLabel();
        creditCardDOI1 = new javax.swing.JLabel();
        financialLabel1 = new javax.swing.JLabel();
        savingsRadioButton1 = new javax.swing.JRadioButton();
        checkingRadioButton1 = new javax.swing.JRadioButton();
        accountStatusLabel2 = new javax.swing.JLabel();
        accountStatusCombo1 = new javax.swing.JComboBox<>();
        accountLabel10 = new javax.swing.JLabel();
        accountLabel11 = new javax.swing.JLabel();
        creationDateAccountTxt1 = new javax.swing.JTextField();
        accountLabel12 = new javax.swing.JLabel();
        secHolderTxtField1 = new javax.swing.JTextField();
        accountStatusLabel3 = new javax.swing.JLabel();
        sAccountStatusCombo1 = new javax.swing.JComboBox<>();
        sAccCreationDateAccountTxt1 = new javax.swing.JTextField();
        accountLabel14 = new javax.swing.JLabel();
        sAccSecHolderTxtField1 = new javax.swing.JTextField();
        sCreditAmtTextField1 = new javax.swing.JTextField();
        accountLabel15 = new javax.swing.JLabel();
        debtAmtTextField2 = new javax.swing.JTextField();
        accountLabel16 = new javax.swing.JLabel();
        sDebtAmtTextField2 = new javax.swing.JTextField();
        accountLabel17 = new javax.swing.JLabel();
        cCreditAmtTextField2 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        lastNameLabel6 = new javax.swing.JLabel();
        maleRadio = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        dobTextField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        Married1 = new javax.swing.JRadioButton();
        singleStatus = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        spouseNameTextField = new javax.swing.JTextField();
        lastNameLabel7 = new javax.swing.JLabel();
        spouseLastNameTextField = new javax.swing.JTextField();
        emailID3 = new javax.swing.JLabel();
        spouseEmailTextField = new javax.swing.JTextField();
        licenseNumLabel3 = new javax.swing.JLabel();
        spouseLicenseNum = new javax.swing.JTextField();
        licenseDOILabel3 = new javax.swing.JLabel();
        spouseDOIText = new javax.swing.JTextField();
        licenseExpiryLabel3 = new javax.swing.JLabel();
        spouseExpDateText = new javax.swing.JTextField();
        attachButtonSpouse = new javax.swing.JButton();
        photoLabelSpouse = new javax.swing.JLabel();
        pathTextFieldSpouse = new javax.swing.JTextField();
        submitButton1 = new javax.swing.JButton();
        creditCardNameLabel2 = new javax.swing.JLabel();
        spouseCreditCardNumText = new javax.swing.JTextField();
        creditCardDOE3 = new javax.swing.JLabel();
        spouseCreExpText = new javax.swing.JTextField();
        bankLabel2 = new javax.swing.JLabel();
        spouseBankTextField = new javax.swing.JTextField();
        femaleRadioButton2 = new javax.swing.JRadioButton();
        licenseNumTextField = new javax.swing.JTextField();
        licenseDOITextField = new javax.swing.JTextField();
        ExpiryDateTextField = new javax.swing.JTextField();
        licenseClassTextField = new javax.swing.JTextField();
        licensePlaceTextField = new javax.swing.JTextField();
        creditNumTxtField1 = new javax.swing.JTextField();
        creditDOETxtField1 = new javax.swing.JTextField();
        creditDOITxtField = new javax.swing.JTextField();
        creditPlaceTxtField = new javax.swing.JTextField();
        bankTxtField = new javax.swing.JTextField();
        stateTextField = new javax.swing.JTextField();
        countryTextField = new javax.swing.JTextField();
        pincodeTextField = new javax.swing.JTextField();
        accountLabel5 = new javax.swing.JLabel();
        firstNameLabel2 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerForCreate.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        headerForCreate.setForeground(new java.awt.Color(0, 51, 102));
        headerForCreate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerForCreate.setText("Fill in your Details");
        headerForCreate.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        add(headerForCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 388, -1));
        headerForCreate.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Address");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 143, 26));

        jLabel4.setText("State");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel5.setText("Country");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jLabel6.setText("Pin Code");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        photoLabel.setText("         Your Photo");
        photoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(photoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 80, 181, 163));

        pathTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextFieldActionPerformed(evt);
            }
        });
        add(pathTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 250, 239, -1));

        attachButton.setText("Attach");
        attachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButtonActionPerformed(evt);
            }
        });
        add(attachButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 250, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("License Data");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        licenseNumLabel.setText("License Number");
        add(licenseNumLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        licenseDOILabel.setText("Date of Issue");
        add(licenseDOILabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        licenseExpiryLabel.setText("Expiry Date");
        add(licenseExpiryLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        licenseClassLabel.setText("Class");
        add(licenseClassLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        licensePlaceOfIssueLabel.setText("Place Of Issuance");
        add(licensePlaceOfIssueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Credit Card");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, -1, -1));

        creditCardNameLabel.setText("Credit Card Number ");
        add(creditCardNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        issuancePlaceLabel.setText("Issuance Place");
        add(issuancePlaceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, -1));

        creditCardDOE1.setText("Credit Card Expiry");
        add(creditCardDOE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));

        bankLabel.setText("Bank");
        add(bankLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        creditCardDOI.setText("Issue Date");
        add(creditCardDOI, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, -1));

        financialLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        financialLabel.setText("Financial Accounts Section");
        add(financialLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        savingsRadioButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        savingsRadioButton.setText("Savings Account");
        savingsRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                savingsRadioButtonStateChanged(evt);
            }
        });
        savingsRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsRadioButtonActionPerformed(evt);
            }
        });
        add(savingsRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        checkingRadioButton.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkingRadioButton.setText("Checkings Account");
        checkingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingRadioButtonActionPerformed(evt);
            }
        });
        add(checkingRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, -1, -1));

        accountStatusLabel.setText("Status");
        add(accountStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, -1, -1));

        accountStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Not Active" }));
        accountStatusCombo.setEnabled(false);
        add(accountStatusCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 440, -1, -1));

        accountLabel2.setText("Secondary Holder");
        add(accountLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 530, -1, -1));

        accountLabel3.setText("Debt Amount");
        add(accountLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, -1, -1));

        creationDateAccountTxt.setEnabled(false);
        add(creationDateAccountTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 560, 143, -1));

        accountLabel4.setText("Creation Date");
        add(accountLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 570, -1, -1));

        secHolderTxtField.setEnabled(false);
        add(secHolderTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 520, 143, -1));

        accountStatusLabel1.setText("Status");
        add(accountStatusLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        sAccountStatusCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Not Active" }));
        sAccountStatusCombo.setEnabled(false);
        add(sAccountStatusCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        sCreditAmtTextField.setEnabled(false);
        add(sCreditAmtTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, 143, -1));

        accountLabel6.setText("Credit Amount");
        add(accountLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 610, -1, -1));

        debtAmtTextField1.setEnabled(false);
        add(debtAmtTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 480, 143, -1));

        accountLabel8.setText("Debt Amount");
        add(accountLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, -1, -1));

        sDebtAmtTextField1.setEnabled(false);
        add(sDebtAmtTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 143, -1));

        accountLabel9.setText("Credit Amount");
        add(accountLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, -1, -1));

        cCreditAmtTextField1.setEnabled(false);
        add(cCreditAmtTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 600, 143, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Basic Info");
        jLabel9.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setText("Spouse Info ");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerForCreate1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        headerForCreate1.setForeground(new java.awt.Color(0, 51, 102));
        headerForCreate1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerForCreate1.setText("Fill in your Details");
        headerForCreate1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.add(headerForCreate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 388, -1));

        lastNameLabel4.setText("Last Name");
        jPanel1.add(lastNameLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 143, 26));

        firstNameLabel3.setText("First Name");
        jPanel1.add(firstNameLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 143, 26));

        emailID2.setText("Email ID");
        jPanel1.add(emailID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 143, 26));

        lastNameLabel5.setText("Gender");
        jPanel1.add(lastNameLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 143, 26));

        lastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 143, -1));

        firstNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 143, -1));

        phoneNumberTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNumberTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(phoneNumberTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 143, -1));

        emailIDTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIDTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(emailIDTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 143, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Address");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 143, 26));

        jLabel14.setText("Street Name");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jLabel15.setText("City");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, -1));

        jLabel16.setText("State");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel17.setText("Country");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, -1, -1));

        jLabel18.setText("Pin Code");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, -1, -1));

        streetNameTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                streetNameTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(streetNameTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 450, 143, -1));

        cityTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cityTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(cityTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 143, -1));

        photoLabel1.setText("         Your Photo");
        photoLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(photoLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 80, 181, 163));

        pathTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(pathTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 250, 239, -1));

        attachButton1.setText("Attach");
        attachButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(attachButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 250, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("License Data");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        licenseNumLabel2.setText("License Number");
        jPanel1.add(licenseNumLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));

        licenseDOILabel2.setText("Date of Issue");
        jPanel1.add(licenseDOILabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, -1, -1));

        licenseExpiryLabel2.setText("Expiry Date");
        jPanel1.add(licenseExpiryLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, -1, -1));

        licenseClassLabel1.setText("Class");
        jPanel1.add(licenseClassLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, -1, -1));

        licensePlaceOfIssueLabel1.setText("Place Of Issuance");
        jPanel1.add(licensePlaceOfIssueLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Credit Card");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, -1, -1));

        creditCardNameLabel1.setText("Credit Card Number ");
        jPanel1.add(creditCardNameLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 110, -1, -1));

        issuancePlaceLabel1.setText("Issuance Place");
        jPanel1.add(issuancePlaceLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 230, -1, -1));

        creditCardDOE2.setText("Credit Card Expiry");
        jPanel1.add(creditCardDOE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, -1, -1));

        bankLabel1.setText("Bank");
        jPanel1.add(bankLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 270, -1, -1));

        creditCardDOI1.setText("Issue Date");
        jPanel1.add(creditCardDOI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 190, -1, -1));

        financialLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        financialLabel1.setText("Financial Accounts Section");
        jPanel1.add(financialLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, -1, -1));

        savingsRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        savingsRadioButton1.setText("Savings Account");
        savingsRadioButton1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                savingsRadioButton1StateChanged(evt);
            }
        });
        savingsRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingsRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(savingsRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, -1, -1));

        checkingRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        checkingRadioButton1.setText("Checkings Account");
        checkingRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(checkingRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 400, -1, -1));

        accountStatusLabel2.setText("Status");
        jPanel1.add(accountStatusLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 450, -1, -1));

        accountStatusCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Not Active" }));
        accountStatusCombo1.setEnabled(false);
        jPanel1.add(accountStatusCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 440, -1, -1));

        accountLabel10.setText("Secondary Holder");
        jPanel1.add(accountLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 530, -1, -1));

        accountLabel11.setText("Debt Amount");
        jPanel1.add(accountLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 490, -1, -1));

        creationDateAccountTxt1.setEnabled(false);
        jPanel1.add(creationDateAccountTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 560, 143, -1));

        accountLabel12.setText("Creation Date");
        jPanel1.add(accountLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 570, -1, -1));

        secHolderTxtField1.setEnabled(false);
        jPanel1.add(secHolderTxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 520, 143, -1));

        accountStatusLabel3.setText("Status");
        jPanel1.add(accountStatusLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 460, -1, -1));

        sAccountStatusCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Active", "Not Active" }));
        sAccountStatusCombo1.setEnabled(false);
        jPanel1.add(sAccountStatusCombo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, -1, -1));

        sAccCreationDateAccountTxt1.setEnabled(false);
        jPanel1.add(sAccCreationDateAccountTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 530, 143, -1));

        accountLabel14.setText("Creation Date");
        jPanel1.add(accountLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, -1));

        sAccSecHolderTxtField1.setEnabled(false);
        jPanel1.add(sAccSecHolderTxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 143, -1));

        sCreditAmtTextField1.setEnabled(false);
        jPanel1.add(sCreditAmtTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 610, 143, -1));

        accountLabel15.setText("Credit Amount");
        jPanel1.add(accountLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 610, -1, -1));

        debtAmtTextField2.setEnabled(false);
        jPanel1.add(debtAmtTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 480, 143, -1));

        accountLabel16.setText("Debt Amount");
        jPanel1.add(accountLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 580, -1, -1));

        sDebtAmtTextField2.setEnabled(false);
        jPanel1.add(sDebtAmtTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 570, 143, -1));

        accountLabel17.setText("Credit Amount");
        jPanel1.add(accountLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 620, -1, -1));

        cCreditAmtTextField2.setEnabled(false);
        jPanel1.add(cCreditAmtTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 600, 143, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel21.setText("Basic Info");
        jLabel21.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        lastNameLabel6.setText("Date Of Birth");
        jPanel1.add(lastNameLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 143, 26));

        maleRadio.setText("Male");
        jPanel1.add(maleRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 30));

        jLabel22.setText("Phone Number");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        dobTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(dobTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 143, -1));

        jLabel23.setText("Marital Status");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        Married1.setText("Married");
        Married1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Married1ActionPerformed(evt);
            }
        });
        jPanel1.add(Married1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        singleStatus.setText("Single");
        singleStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singleStatusActionPerformed(evt);
            }
        });
        jPanel1.add(singleStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel24.setText("Spouse Info ");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, -1, -1));

        spouseNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(spouseNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 710, 143, -1));

        lastNameLabel7.setText("Last Name");
        jPanel1.add(lastNameLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 750, 143, 26));

        spouseLastNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseLastNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(spouseLastNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 750, 143, -1));

        emailID3.setText("Email ID");
        jPanel1.add(emailID3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 790, 143, 26));

        spouseEmailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseEmailTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(spouseEmailTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 790, 143, -1));

        licenseNumLabel3.setText("License Number");
        jPanel1.add(licenseNumLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 710, -1, -1));

        spouseLicenseNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseLicenseNumActionPerformed(evt);
            }
        });
        jPanel1.add(spouseLicenseNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 710, 143, -1));

        licenseDOILabel3.setText("Date of Issue");
        jPanel1.add(licenseDOILabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 750, -1, -1));

        spouseDOIText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseDOITextActionPerformed(evt);
            }
        });
        jPanel1.add(spouseDOIText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 750, 143, -1));

        licenseExpiryLabel3.setText("Expiry Date");
        jPanel1.add(licenseExpiryLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 790, -1, -1));

        spouseExpDateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseExpDateTextActionPerformed(evt);
            }
        });
        jPanel1.add(spouseExpDateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 790, 143, -1));

        attachButtonSpouse.setText("Attach");
        attachButtonSpouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButtonSpouseActionPerformed(evt);
            }
        });
        jPanel1.add(attachButtonSpouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 830, -1, -1));

        photoLabelSpouse.setText("         Your Photo");
        photoLabelSpouse.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(photoLabelSpouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 660, 181, 163));

        pathTextFieldSpouse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathTextFieldSpouseActionPerformed(evt);
            }
        });
        jPanel1.add(pathTextFieldSpouse, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 830, 239, -1));

        submitButton1.setText("Submit");
        submitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(submitButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 840, -1, -1));

        creditCardNameLabel2.setText("Credit Card Number ");
        jPanel1.add(creditCardNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 710, -1, -1));
        jPanel1.add(spouseCreditCardNumText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 710, 143, -1));

        creditCardDOE3.setText("Credit Card Expiry");
        jPanel1.add(creditCardDOE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 750, -1, -1));
        jPanel1.add(spouseCreExpText, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 750, 143, -1));

        bankLabel2.setText("Bank");
        jPanel1.add(bankLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 790, -1, -1));

        spouseBankTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spouseBankTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(spouseBankTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 790, 143, -1));

        femaleRadioButton2.setText("Female");
        jPanel1.add(femaleRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, -1, 30));

        licenseNumTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseNumTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(licenseNumTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 143, -1));

        licenseDOITextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseDOITextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(licenseDOITextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 143, -1));

        ExpiryDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExpiryDateTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(ExpiryDateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 143, -1));

        licenseClassTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licenseClassTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(licenseClassTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 230, 143, -1));

        licensePlaceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licensePlaceTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(licensePlaceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 143, -1));
        jPanel1.add(creditNumTxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 110, 143, -1));
        jPanel1.add(creditDOETxtField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 150, 143, -1));
        jPanel1.add(creditDOITxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 143, -1));
        jPanel1.add(creditPlaceTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 230, 143, -1));
        jPanel1.add(bankTxtField, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 270, 143, -1));

        stateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(stateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 530, 143, -1));

        countryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(countryTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 570, 143, -1));

        pincodeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pincodeTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(pincodeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 620, 143, -1));

        accountLabel5.setText("Secondary Holder");
        jPanel1.add(accountLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 500, -1, -1));

        firstNameLabel2.setText("First Name");
        jPanel1.add(firstNameLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 710, 143, 26));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void attachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButtonActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        pathTextField.setText(filename);
        BufferedImage image;
        try {
            image = ImageIO.read(file);
            Image resizedImg = image.getScaledInstance(photoLabel.getWidth(), photoLabel.getHeight(),
                    Image.SCALE_SMOOTH);
            photoLabel.setIcon(new ImageIcon(resizedImg));
            person.setPicture(image);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Attach the image properly");

            Logger.getLogger(CreateProfileJForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_attachButtonActionPerformed

    private void licensePlaceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licensePlaceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licensePlaceTextFieldActionPerformed

    private void licenseClassTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseClassTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseClassTextFieldActionPerformed

    private void ExpiryDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExpiryDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExpiryDateTextFieldActionPerformed

    private void licenseDOITextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseDOITextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseDOITextFieldActionPerformed

    private void licenseNumTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licenseNumTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licenseNumTextFieldActionPerformed

    private void pathTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextFieldActionPerformed

    private void countryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTextFieldActionPerformed

    private void stateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextFieldActionPerformed

    private void pincodeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pincodeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pincodeTextFieldActionPerformed

    private void savingsRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsRadioButtonActionPerformed

        // TODO add your handling code here:
        if (savingsRadioButton.isEnabled()) {
            sAccSecHolderTxtField1.setEnabled(true);
            sAccCreationDateAccountTxt1.setEnabled(true);
            sAccountStatusCombo.setEnabled(true);
            sDebtAmtTextField1.setEnabled(true);
            sCreditAmtTextField.setEnabled(true);
        }
    }//GEN-LAST:event_savingsRadioButtonActionPerformed

    private void savingsRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_savingsRadioButtonStateChanged

    }//GEN-LAST:event_savingsRadioButtonStateChanged

    private void checkingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingRadioButtonActionPerformed
        // Enable only when the radio is selected
        if (checkingRadioButton.isEnabled()) {
            secHolderTxtField.setEnabled(true);
            accountStatusCombo.setEnabled(true);
            debtAmtTextField1.setEnabled(true);
            cCreditAmtTextField1.setEnabled(true);
            creationDateAccountTxt.setEnabled(true);
        }
    }//GEN-LAST:event_checkingRadioButtonActionPerformed

    private void lastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextFieldActionPerformed

    private void firstNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextFieldActionPerformed

    private void phoneNumberTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNumberTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNumberTextField1ActionPerformed

    private void emailIDTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIDTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIDTextFieldActionPerformed

    private void streetNameTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_streetNameTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_streetNameTextField3ActionPerformed

    private void cityTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cityTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cityTextField2ActionPerformed

    private void pathTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextField1ActionPerformed

    private void attachButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attachButton1ActionPerformed

    private void savingsRadioButton1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_savingsRadioButton1StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsRadioButton1StateChanged

    private void savingsRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingsRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingsRadioButton1ActionPerformed

    private void checkingRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingRadioButton1ActionPerformed

    private void dobTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dobTextFieldActionPerformed

    private void Married1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Married1ActionPerformed
        // TODO add your handling code here:
        if (Married1.isEnabled()) {
            spouseNameTextField.setEnabled(true);
            spouseLastNameTextField.setEnabled(true);
            spouseEmailTextField.setEnabled(true);
            spouseLicenseNum.setEnabled(true);
            spouseExpDateText.setEnabled(true);
            spouseDOIText.setEnabled(true);
            spouseBankTextField.setEnabled(true);
            spouseCreditCardNumText.setEnabled(true);
            spouseCreExpText.setEnabled(true);
            attachButtonSpouse.setEnabled(true);
            pathTextFieldSpouse.setEnabled(true);
            photoLabelSpouse.setEnabled(true);
    }//GEN-LAST:event_Married1ActionPerformed
    }
    private void spouseNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseNameTextFieldActionPerformed

    private void spouseLastNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseLastNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseLastNameTextFieldActionPerformed

    private void spouseEmailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseEmailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseEmailTextFieldActionPerformed

    private void spouseLicenseNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseLicenseNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseLicenseNumActionPerformed

    private void spouseDOITextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseDOITextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseDOITextActionPerformed

    private void spouseExpDateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseExpDateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseExpDateTextActionPerformed

    private void pathTextFieldSpouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathTextFieldSpouseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pathTextFieldSpouseActionPerformed

    private void attachButtonSpouseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButtonSpouseActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        String filename = file.getAbsolutePath();
        pathTextFieldSpouse.setText(filename);
        BufferedImage image;
        try {
            image = ImageIO.read(file);
            Image resizedImg = image.getScaledInstance(photoLabelSpouse.getWidth(), photoLabelSpouse.getHeight(),
                    Image.SCALE_SMOOTH);
            photoLabelSpouse.setIcon(new ImageIcon(resizedImg));
            spouse.setPicture(image);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Attach the image properly");
            Logger.getLogger(CreateProfileJForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_attachButtonSpouseActionPerformed

    private void submitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButton1ActionPerformed
        person.setFirstName(firstNameTextField.getText());
        person.setLastName(lastNameTextField.getText());
        person.setEmailID(emailIDTextField.getText());
        DateFormat df = new SimpleDateFormat("MM/dd/yyyy");
        // Date date = df.parse(dobTextField2);
//         Date date = new Date();
//   System.out.println(df.format(date));
//   dobTextField2.setText(df.format(date));
//JFormattedTextField txtDate = new JFormattedTextField(df);
//person.setDate(date);
        try {
            person.setDate(df.parse(dobTextField.getText()));
            person.setPhoneNum(phoneNumberTextField1.getText());
            if (maleRadio.isEnabled()) {
                person.setGenderValue("Male");
            } else {
                person.setGenderValue("Female");
            }
            address.setCityName(cityTextField2.getText());
            address.setStreetName(streetNameTextField3.getText());
            address.setStateName(stateTextField.getText());
            address.setPinCode(pincodeTextField.getText());
            address.setCountryName(countryTextField.getText());
            person.setAddress(address);
            licenseData.setDateOfIssuance(df.parse(licenseDOITextField.getText()));
            licenseData.setTypeOfClass(licenseClassTextField.getText());
            licenseData.setLicenseExpDate(df.parse(ExpiryDateTextField.getText()));
            licenseData.setPlaceOfIssuance(licensePlaceTextField.getText());
            licenseData.setLicenseNum(licenseNumTextField.getText());
            person.setLicenseData(licenseData);
            creditCard.setCreditBank(bankTxtField.getText());
            creditCard.setCreditExpiry(df.parse(creditDOETxtField1.getText()));
            creditCard.setCreditIssueDate(df.parse(creditDOITxtField.getText()));
            creditCard.setCreditIssuePlace(creditPlaceTxtField.getText());
            creditCard.setCreditNum(creditNumTxtField1.getText());
            person.setCreditCard(creditCard);
            finAccounts.getCheckingAccount().setAccountStatus(accountStatusCombo.getSelectedItem().toString());
            // finAccounts.getCheckingAccount().
            finAccounts.getCheckingAccount().setAccountDate(creationDateAccountTxt.getText());
            finAccounts.getCheckingAccount().setAccountSecHolderName(secHolderTxtField.getText());

            finAccounts.getCheckingAccount().setAccountCredit(cCreditAmtTextField1.getText());
            finAccounts.getCheckingAccount().setAccountDebt(debtAmtTextField1.getText());

            finAccounts.getSavingsAccount().setAccountDebt(sDebtAmtTextField1.getText());
            finAccounts.getSavingsAccount().setAccountDate(sAccCreationDateAccountTxt1.getText());
            finAccounts.getSavingsAccount().setAccountSecHolderName(sAccSecHolderTxtField1.getText());
            finAccounts.getSavingsAccount().setAccountCredit(sCreditAmtTextField.getText());
            finAccounts.getSavingsAccount().setAccountStatus(sAccountStatusCombo.getSelectedItem().toString());
            person.setFinAccounts(finAccounts);
            if (Married1.isEnabled() && Married1.isSelected()) {
                spouse.setFirstName(spouseNameTextField.getText());
                spouse.setLastName(spouseLastNameTextField.getText());
                spouse.setEmailID(spouseEmailTextField.getText());
//        
                spouseCreditCard.setCreditBank(spouseBankTextField.getText());
                spouseCreditCard.setCreditNum(spouseCreditCardNumText.getText());
                spouseCreditCard.setCreditExpiry(df.parse(spouseCreExpText.getText()));
                
                spouseLicence.setLicenseNum(spouseLicenseNum.getText());
                
               spouseLicence.setLicenseExpDate(df.parse(spouseExpDateText.getText()));
               spouseLicence.setDateOfIssuance(df.parse(spouseDOIText.getText()));
//        
                
//                
//                spouse.getLicenseData().setLicenseNum(spouseLicenseNum.getText());
//                spouse.getLicenseData().setLicenseExpDate(df.parse(spouseExpDateText.getText()));
//                spouse.getLicenseData().setDateOfIssuance(df.parse(spouseDOIText.getText()));
////        
//                spouse.getCreditCard().setCreditBank(spouseBankTextField.getText());
//                spouse.getCreditCard().setCreditNum(spouseCreditCardNumText.getText());
//                spouse.getCreditCard().setCreditExpiry(df.parse(spouseCreExpText.getText()));

// 

spouse.setCreditCard(spouseCreditCard);
spouse.setLicenseData(spouseLicence);

            }
            
//            else if(singleStatus.isSelected()){
//                spouse.setFirstName("");
//                spouse.setLastName("");
//                spouse.setEmailID("");
////        
//                spouseCreditCard.setCreditBank("");
//                spouseCreditCard.setCreditNum("");
//                spouseCreditCard.setCreditExpiry(null);
//                
//                spouseLicence.setLicenseNum("");
//                
//               spouseLicence.setLicenseExpDate(null);
//               spouseLicence.setDateOfIssuance(null);
//               
//                
//                 
//                
//            }
            JOptionPane.showMessageDialog(null, "User Profile is successfully recorded");
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Error in date format - Date it should be of type MM/DD/YYYY");
            Logger.getLogger(CreateProfileJForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_submitButton1ActionPerformed

    private void spouseBankTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spouseBankTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_spouseBankTextFieldActionPerformed

    private void singleStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_singleStatusActionPerformed
        // TODO add your handling code here:
        if (singleStatus.isEnabled() && singleStatus.isSelected()) {
            spouseNameTextField.setEnabled(false);
            spouseLastNameTextField.setEnabled(false);
            spouseEmailTextField.setEnabled(false);
            spouseLicenseNum.setEnabled(false);
            spouseExpDateText.setEnabled(false);
            spouseDOIText.setEnabled(false);
            spouseBankTextField.setEnabled(false);
            spouseCreditCardNumText.setEnabled(false);
            spouseCreExpText.setEnabled(false);
            attachButtonSpouse.setEnabled(false);
            pathTextFieldSpouse.setEnabled(false);
            photoLabelSpouse.setEnabled(false);
    }//GEN-LAST:event_singleStatusActionPerformed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ExpiryDateTextField;
    private javax.swing.JRadioButton Married1;
    private javax.swing.JLabel accountLabel10;
    private javax.swing.JLabel accountLabel11;
    private javax.swing.JLabel accountLabel12;
    private javax.swing.JLabel accountLabel14;
    private javax.swing.JLabel accountLabel15;
    private javax.swing.JLabel accountLabel16;
    private javax.swing.JLabel accountLabel17;
    private javax.swing.JLabel accountLabel2;
    private javax.swing.JLabel accountLabel3;
    private javax.swing.JLabel accountLabel4;
    private javax.swing.JLabel accountLabel5;
    private javax.swing.JLabel accountLabel6;
    private javax.swing.JLabel accountLabel8;
    private javax.swing.JLabel accountLabel9;
    private javax.swing.JComboBox<String> accountStatusCombo;
    private javax.swing.JComboBox<String> accountStatusCombo1;
    private javax.swing.JLabel accountStatusLabel;
    private javax.swing.JLabel accountStatusLabel1;
    private javax.swing.JLabel accountStatusLabel2;
    private javax.swing.JLabel accountStatusLabel3;
    private javax.swing.JButton attachButton;
    private javax.swing.JButton attachButton1;
    private javax.swing.JButton attachButtonSpouse;
    private javax.swing.JLabel bankLabel;
    private javax.swing.JLabel bankLabel1;
    private javax.swing.JLabel bankLabel2;
    private javax.swing.JTextField bankTxtField;
    private javax.swing.ButtonGroup buttonGroupForGender;
    private javax.swing.ButtonGroup buttonGroupForMaritalStatus;
    private javax.swing.JTextField cCreditAmtTextField1;
    private javax.swing.JTextField cCreditAmtTextField2;
    private javax.swing.JRadioButton checkingRadioButton;
    private javax.swing.JRadioButton checkingRadioButton1;
    private javax.swing.JTextField cityTextField2;
    private javax.swing.JTextField countryTextField;
    private javax.swing.JTextField creationDateAccountTxt;
    private javax.swing.JTextField creationDateAccountTxt1;
    private javax.swing.JLabel creditCardDOE1;
    private javax.swing.JLabel creditCardDOE2;
    private javax.swing.JLabel creditCardDOE3;
    private javax.swing.JLabel creditCardDOI;
    private javax.swing.JLabel creditCardDOI1;
    private javax.swing.JLabel creditCardNameLabel;
    private javax.swing.JLabel creditCardNameLabel1;
    private javax.swing.JLabel creditCardNameLabel2;
    private javax.swing.JTextField creditDOETxtField1;
    private javax.swing.JTextField creditDOITxtField;
    private javax.swing.JTextField creditNumTxtField1;
    private javax.swing.JTextField creditPlaceTxtField;
    private javax.swing.JTextField debtAmtTextField1;
    private javax.swing.JTextField debtAmtTextField2;
    private javax.swing.JTextField dobTextField;
    private javax.swing.JLabel emailID2;
    private javax.swing.JLabel emailID3;
    private javax.swing.JTextField emailIDTextField;
    private javax.swing.JRadioButton femaleRadioButton2;
    private javax.swing.JLabel financialLabel;
    private javax.swing.JLabel financialLabel1;
    private javax.swing.JLabel firstNameLabel2;
    private javax.swing.JLabel firstNameLabel3;
    private javax.swing.JTextField firstNameTextField;
    private javax.swing.JLabel headerForCreate;
    private javax.swing.JLabel headerForCreate1;
    private javax.swing.JLabel issuancePlaceLabel;
    private javax.swing.JLabel issuancePlaceLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel4;
    private javax.swing.JLabel lastNameLabel5;
    private javax.swing.JLabel lastNameLabel6;
    private javax.swing.JLabel lastNameLabel7;
    private javax.swing.JTextField lastNameTextField;
    private javax.swing.JLabel licenseClassLabel;
    private javax.swing.JLabel licenseClassLabel1;
    private javax.swing.JTextField licenseClassTextField;
    private javax.swing.JLabel licenseDOILabel;
    private javax.swing.JLabel licenseDOILabel2;
    private javax.swing.JLabel licenseDOILabel3;
    private javax.swing.JTextField licenseDOITextField;
    private javax.swing.JLabel licenseExpiryLabel;
    private javax.swing.JLabel licenseExpiryLabel2;
    private javax.swing.JLabel licenseExpiryLabel3;
    private javax.swing.JLabel licenseNumLabel;
    private javax.swing.JLabel licenseNumLabel2;
    private javax.swing.JLabel licenseNumLabel3;
    private javax.swing.JTextField licenseNumTextField;
    private javax.swing.JLabel licensePlaceOfIssueLabel;
    private javax.swing.JLabel licensePlaceOfIssueLabel1;
    private javax.swing.JTextField licensePlaceTextField;
    private javax.swing.JRadioButton maleRadio;
    private javax.swing.JTextField pathTextField;
    private javax.swing.JTextField pathTextField1;
    private javax.swing.JTextField pathTextFieldSpouse;
    private javax.swing.JTextField phoneNumberTextField1;
    private javax.swing.JLabel photoLabel;
    private javax.swing.JLabel photoLabel1;
    private javax.swing.JLabel photoLabelSpouse;
    private javax.swing.JTextField pincodeTextField;
    private javax.swing.JTextField sAccCreationDateAccountTxt1;
    private javax.swing.JTextField sAccSecHolderTxtField1;
    private javax.swing.JComboBox<String> sAccountStatusCombo;
    private javax.swing.JComboBox<String> sAccountStatusCombo1;
    private javax.swing.JTextField sCreditAmtTextField;
    private javax.swing.JTextField sCreditAmtTextField1;
    private javax.swing.JTextField sDebtAmtTextField1;
    private javax.swing.JTextField sDebtAmtTextField2;
    private javax.swing.JRadioButton savingsRadioButton;
    private javax.swing.JRadioButton savingsRadioButton1;
    private javax.swing.JTextField secHolderTxtField;
    private javax.swing.JTextField secHolderTxtField1;
    private javax.swing.JRadioButton singleStatus;
    private javax.swing.JTextField spouseBankTextField;
    private javax.swing.JTextField spouseCreExpText;
    private javax.swing.JTextField spouseCreditCardNumText;
    private javax.swing.JTextField spouseDOIText;
    private javax.swing.JTextField spouseEmailTextField;
    private javax.swing.JTextField spouseExpDateText;
    private javax.swing.JTextField spouseLastNameTextField;
    private javax.swing.JTextField spouseLicenseNum;
    private javax.swing.JTextField spouseNameTextField;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField streetNameTextField3;
    private javax.swing.JButton submitButton1;
    // End of variables declaration//GEN-END:variables
}
