/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import BusinessPackage.Account;
import BusinessPackage.AccountDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ragha
 */
public class ManageAccountJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAccountJPanel
     */
    private JPanel userContainer;
    private AccountDirectory accountDir;

    ManageAccountJPanel(JPanel userContainer, AccountDirectory accountDir) {
        initComponents();

        this.userContainer = userContainer;
        this.accountDir = accountDir;
        populateTable();
    }

    private void populateTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) tableAccount.getModel();
        defaultTableModel.setRowCount(0);
        for (Account account : accountDir.getAccountDirectory()) {
            Object[] row = new Object[4];
            row[0] = account;
            row[1] = account.getAccNum();
            row[2] = account.getBankName();
            row[3] = account.getBalance();
            defaultTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableAccount = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        searchTextField = new javax.swing.JTextField();
        viewButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(900, 600));

        tableAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Routing Number", "Account Number", "Bank Name", "Balance"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableAccount);
        if (tableAccount.getColumnModel().getColumnCount() > 0) {
            tableAccount.getColumnModel().getColumn(0).setResizable(false);
            tableAccount.getColumnModel().getColumn(1).setResizable(false);
            tableAccount.getColumnModel().getColumn(3).setResizable(false);
        }

        searchButton.setText("Search by Account Number ");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        viewButton.setText("View Details");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        backButton.setText("< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(searchButton)
                        .addGap(33, 33, 33)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(246, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(deleteButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(viewButton)
                .addGap(61, 61, 61))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(backButton)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(deleteButton))
                .addContainerGap(340, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Go to the previous page
        userContainer.remove(this);
        CardLayout cardLayout = (CardLayout) userContainer.getLayout();
        cardLayout.previous(userContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // Delete the account detail

        int selectedRows = tableAccount.getSelectedRow();
        if (selectedRows >= 0) {
            int diaButton = JOptionPane.YES_NO_OPTION;
            int diaResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete the account details", "Warning", diaButton);
            if (diaResult == JOptionPane.YES_OPTION) {
                Account account = (Account) tableAccount.getValueAt(selectedRows, 0);
                accountDir.deleteAccount(account);
                populateTable();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Select any row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // View Operation
        int selectedRows = tableAccount.getSelectedRow();
        if (selectedRows < 0) {
            JOptionPane.showMessageDialog(null, "Select any row from the table to view the details", "Warning", JOptionPane.WARNING_MESSAGE);

        } else {
            Account account = (Account) tableAccount.getValueAt(selectedRows, 0);
            ViewAccountJPanel viewAccountJPanel = new ViewAccountJPanel(userContainer, account);
            userContainer.add("ViewAccountJPanel", viewAccountJPanel);
            CardLayout cardLayout = (CardLayout) userContainer.getLayout();
            cardLayout.next(userContainer);

        }
    }//GEN-LAST:event_viewButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // Search
        if(searchTextField.getText() == null || searchTextField.getText().equals(""))
        {
                        JOptionPane.showMessageDialog(null, "Enter a value to search", "Warning", JOptionPane.WARNING_MESSAGE);

        }
        else
        {

        Account result = accountDir.searchAccount(Integer.parseInt(searchTextField.getText()));
        if (result == null) {
            JOptionPane.showMessageDialog(null, "Account Detail does not exists", "Information", JOptionPane.INFORMATION_MESSAGE);

        }
        else {
             ViewAccountJPanel viewAccountJPanel = new ViewAccountJPanel(userContainer, result);
            userContainer.add("ViewAccountJPanel", viewAccountJPanel);
            CardLayout cardLayout = (CardLayout) userContainer.getLayout();
            cardLayout.next(userContainer);
        }
    }//GEN-LAST:event_searchButtonActionPerformed
            
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JTable tableAccount;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
