/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Customer;
import Business.Flight;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class BookCustomersJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BookCustomersJPanel
     */
    JPanel userContainer;
    private Flight flight;
    public BookCustomersJPanel(JPanel userProcessContainer, Flight flight) {
        initComponents();
        this.userContainer=userProcessContainer;
        this.flight = flight;
        populatetheBookedFlightDetails();
    }
  private void populatetheBookedFlightDetails() {
      airlineNameLabel.setText(flight.getAirlineName());
      sourceLabel.setText(flight.getSource());
      destinationLabel.setText(flight.getDestination());
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        bookFlightButton = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        customerFirstName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        airlineNameLabel = new javax.swing.JLabel();
        arrivalTimeLabel = new javax.swing.JLabel();
        depTimeLabel = new javax.swing.JLabel();
        destinationLabel = new javax.swing.JLabel();
        sourceLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lastNameText = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        customerContactText = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Airliner:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 67, -1, -1));

        jLabel3.setText("Source: ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 92, -1, -1));

        jLabel5.setText("Destination:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 117, -1, -1));

        jLabel7.setText("Departure Time:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 142, -1, -1));

        jLabel8.setText("Arrival Time:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 167, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Customer Details");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 198, -1, -1));

        bookFlightButton.setText("Book the flight");
        bookFlightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookFlightButtonActionPerformed(evt);
            }
        });
        add(bookFlightButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, -1, -1));

        jLabel10.setText("First Name");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        add(customerFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 103, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel12.setText("Book Flight for the Customer");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 20, -1, -1));

        backButton.setText("<<back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
        add(airlineNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 80, 20));
        add(arrivalTimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 80, 20));
        add(depTimeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 80, 20));
        add(destinationLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 80, 20));
        add(sourceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 80, 20));

        jLabel2.setText("Last Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));
        add(lastNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 103, -1));

        jLabel4.setText("Contact Number");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));
        add(customerContactText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 103, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
          userContainer.remove(this);
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.previous(userContainer);
   
    }//GEN-LAST:event_backButtonActionPerformed

    private void bookFlightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookFlightButtonActionPerformed
        // TODO add your handling code here:
        Customer customer = flight.addCustomer();
        customer.setCustomerFirstName(customerFirstName.getText());
        customer.setCustomerLastName(lastNameText.getText());
        customer.setMobileNum(customerContactText.getText());
        customer.setFlight(flight);
        //Go ahead and view the Ticket
         EticketJPanel eticketJPanel = new EticketJPanel(userContainer,customer);
        userContainer.add("EticketJPanel", eticketJPanel);
        CardLayout layout = (CardLayout) userContainer.getLayout();
        layout.next(userContainer);
    
    }//GEN-LAST:event_bookFlightButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlineNameLabel;
    private javax.swing.JLabel arrivalTimeLabel;
    private javax.swing.JButton backButton;
    private javax.swing.JButton bookFlightButton;
    private javax.swing.JTextField customerContactText;
    private javax.swing.JTextField customerFirstName;
    private javax.swing.JLabel depTimeLabel;
    private javax.swing.JLabel destinationLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel sourceLabel;
    // End of variables declaration//GEN-END:variables

  
}
