/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class ManageCustomersWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCustomersWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private TravelAgency airlineDirectory;
    public ManageCustomersWorkAreaJPanel(JPanel userProcessContainer,TravelAgency airlineDirectory) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.airlineDirectory = airlineDirectory;
        
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bestDealButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Manage Customers");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        bestDealButton.setText("Search for Flights Best Deals");
        bestDealButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestDealButtonActionPerformed(evt);
            }
        });
        add(bestDealButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 106, 320, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void bestDealButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestDealButtonActionPerformed
        // TODO add your handling code here:
        ViewBestFlightDealsJPanel panel = new ViewBestFlightDealsJPanel(userProcessContainer,airlineDirectory);
        userProcessContainer.add("ViewBestFlightDealsJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_bestDealButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bestDealButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
