/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageCustomers;

import Business.Airline;
import Business.Flight;
import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ViewBestFlightDealsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewBestFlightDealsJPanel
     */
    private JPanel userProcessContainer;
    private TravelAgency airlineDirectory;
    public ViewBestFlightDealsJPanel(JPanel userProcessContainer, TravelAgency airlineDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.airlineDirectory = airlineDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        priceSearchText = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sourceTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        destTextField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        serachAndBookButton = new javax.swing.JButton();
        backButton_customer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bestDealTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Best Deals");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        priceSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceSearchTextActionPerformed(evt);
            }
        });
        add(priceSearchText, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 83, 140, -1));

        jLabel2.setText("Price");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 86, -1, -1));

        jLabel3.setText("Source ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 117, -1, -1));
        add(sourceTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 114, 140, -1));

        jLabel4.setText("Destination");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 148, -1, -1));

        destTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destTextFieldActionPerformed(evt);
            }
        });
        add(destTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 145, 140, -1));

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        add(searchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        serachAndBookButton.setText("Select And Book");
        serachAndBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serachAndBookButtonActionPerformed(evt);
            }
        });
        add(serachAndBookButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 374, -1, -1));

        backButton_customer.setText("<<back");
        backButton_customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton_customerActionPerformed(evt);
            }
        });
        add(backButton_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        bestDealTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight Name", "Airliner", "Depature Date", "Price", "Flight Number"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bestDealTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 560, 130));
    }// </editor-fold>//GEN-END:initComponents

    private void serachAndBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serachAndBookButtonActionPerformed
        // TODO add your handling code here:
           int selectedRow = bestDealTable.getSelectedRow();
        if (selectedRow >= 0) 
        {
            Flight flight = (Flight) bestDealTable.getValueAt((Integer) selectedRow, 0);
     
        BookCustomersJPanel panel = new BookCustomersJPanel(userProcessContainer,flight);
        userProcessContainer.add("BookCustomersJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else
        {
            
            JOptionPane.showMessageDialog(null, "Select any row from the table to view the details", "Warning", JOptionPane.WARNING_MESSAGE);

        
        }
    }//GEN-LAST:event_serachAndBookButtonActionPerformed

    private void backButton_customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton_customerActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton_customerActionPerformed

    private void priceSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceSearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceSearchTextActionPerformed

    private void destTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destTextFieldActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel defaultTableModel = (DefaultTableModel) bestDealTable.getModel();
        defaultTableModel.setRowCount(0);
        for (Airline airline : airlineDirectory.getTravelAgency()) {
            for (Flight f : airline.getFleet().getFleet()) {
                if ((f.getPrice() <= Integer.parseInt(priceSearchText.getText())) && f.getSource().equalsIgnoreCase(sourceTextField.getText()) && (f.getDestination().equalsIgnoreCase(destTextField.getText()))) {
                    Object[] row = new Object[5];
                    row[0] = f;
                    row[1] = f.getAirlineName();
                    row[2] = f.getDepartureDate();
                    row[3] = f.getPrice();
                    row[4] = f.getFlightSerialNum();
                    defaultTableModel.addRow(row);

                }
            }
        }

    }//GEN-LAST:event_searchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton_customer;
    private javax.swing.JTable bestDealTable;
    private javax.swing.JTextField destTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField priceSearchText;
    private javax.swing.JButton searchButton;
    private javax.swing.JButton serachAndBookButton;
    private javax.swing.JTextField sourceTextField;
    // End of variables declaration//GEN-END:variables
}
