/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageTravelAgency;

import Business.Airline;
import Business.Flight;
import Business.TravelAgency;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ragha
 */
public class ManageTravelAgencyJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageTravelAgencyJPanel
     */
    private JPanel userContainer;
    private TravelAgency airlineDirectory;
    public ManageTravelAgencyJPanel(JPanel userContainer, TravelAgency airlineDirectory) {
        initComponents();
        this.userContainer = userContainer;
        this.airlineDirectory = airlineDirectory;
        try {
            populateTable();
        } catch (ParseException ex) {
            Logger.getLogger(ManageTravelAgencyJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        manageTable = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Flight Name", "Airliner Name", "Source (From)", "Destination", "Flight Serial Number", "Departure Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(manageTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 930, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void populateTable() throws ParseException {
         DefaultTableModel defaultTableModel = (DefaultTableModel) manageTable.getModel();
        defaultTableModel.setRowCount(0);
      
            for (Airline airline : airlineDirectory.getTravelAgency()) {
                {
                    for (Flight f : airline.getFleet().getFleet())
                    {
                         Object[] row = new Object[6];
            row[0] = f;
            row[1] = f.getAirlineName();
            row[2] = f.getSource();
            row[3] = f.getDestination();
            row[4] = f.getFlightSerialNum();
            SimpleDateFormat dateFormat = new SimpleDateFormat("MM-dd-yyyy");
String startDateString = dateFormat.format(f.getDepartureDate());
System.out.println(startDateString);
        //    java.util.Date date = new SimpleDateFormat("MM-dd-yyyy").parse(startDateString);

            row[5] = startDateString;
            
            defaultTableModel.addRow(row);
                        
                    }
                }
            }
       
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable manageTable;
    // End of variables declaration//GEN-END:variables
}
